local lc_enable_gui = has_config("lc_enable_gui")

local function test_proj(name, source, gui_dep, callable, kind)
    if gui_dep and not lc_enable_gui then
        return
    end
    target(name)
    add_deps("lc-backends-dummy", {inherit = false, links = false})
    _config_project({project_kind = kind or "binary"})
    add_files(source)
    add_includedirs("./", "./common")
    add_deps("lc-runtime", "lc-dsl", "lc-vstl", "stb-image")
    if lc_enable_gui then
        add_deps("lc-gui")
    end
    if gui_dep then
        add_defines("LUISA_ENABLE_GUI")
    end
    if callable then
        callable()
    end
    target_end()
end

-- unit/core
test_proj("test_basic_traits", "unit/core/test_basic_traits.cpp")
test_proj("test_basic_types", "unit/core/test_basic_types.cpp")
test_proj("test_binary_file_stream", "unit/core/test_binary_file_stream.cpp")
test_proj("test_binary_io", "unit/core/test_binary_io.cpp")
test_proj("test_clock", "unit/core/test_clock.cpp")
test_proj("test_dynamic_module", "unit/core/test_dynamic_module.cpp")
test_proj("test_first_fit", "unit/core/test_first_fit.cpp")
test_proj("test_logging", "unit/core/test_logging.cpp")
test_proj("test_mathematics", "unit/core/test_mathematics.cpp")
test_proj("test_matrix", "unit/core/test_matrix.cpp")
test_proj("test_pool", "unit/core/test_pool.cpp")
test_proj("test_type", "unit/core/test_type.cpp")
test_proj("test_stl_containers", "unit/core/test_stl_containers.cpp")
test_proj("test_hash", "unit/core/test_hash.cpp")
test_proj("test_spin_mutex", "unit/core/test_spin_mutex.cpp")
test_proj("test_fiber", "unit/core/test_fiber.cpp")
test_proj("test_platform_utils", "unit/core/test_platform.cpp")
test_proj("test_foreground_moments", "unit/core/test_foreground_moments.cpp", false, function()
    add_includedirs("../../examples/common")
end)
test_proj("test_example_options", "unit/core/test_example_options.cpp", false, function()
    add_includedirs("../../examples/common")
end)
test_proj("test_path_tracing_sample_plan", "unit/core/test_path_tracing_sample_plan.cpp", false, function()
    add_includedirs("../../examples/common")
end)
test_proj("test_nbody_render_plan", "unit/core/test_nbody_render_plan.cpp", false, function()
    add_includedirs("../../examples/common")
end)
test_proj("test_photon_mapping_plan", "unit/core/test_photon_mapping_plan.cpp", false, function()
    add_includedirs("../../examples/common")
end)
test_proj("test_sparse_buffer_tile_plan", "unit/core/test_sparse_buffer_tile_plan.cpp", false, function()
    add_includedirs("../runtime")
end)
test_proj("test_sparse_texture_tile_plan", "unit/core/test_sparse_texture_tile_plan.cpp", false, function()
    add_includedirs("../runtime")
end)
test_proj("test_pixel_storage", "unit/core/test_pixel_storage.cpp")
test_proj("test_eastl_allocation", "unit/core/test_eastl_allocation.cpp")
test_proj("test_argument_block_layout", "unit/ext/test_argument_block_layout.cpp", false, function()
    add_includedirs("../backends/common")
end)
test_proj("test_command_reorder_bindless", "unit/ext/test_command_reorder_bindless.cpp", false, function()
    add_includedirs("../backends/common")
end)
if has_config("lc_vk_backend") or has_config("lc_dx_backend") then
    test_proj("test_hlsl_validation_codegen", "unit/ext/test_hlsl_validation_codegen.cpp", false, function()
        add_includedirs("../backends/common/hlsl")
        add_deps("lc-hlsl-codegen", "spirv-tools")
    end)
end

if has_config("lc_vk_backend") and
   (has_config("lc_vk_backend_use_xir_spirv") or
    has_config("lc_vk_backend_use_ast_llvm_spirv")) then
    test_proj("test_spirv_constant_ubo_layout", "unit/ext/test_spirv_constant_ubo_layout.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_optimizer", "unit/ext/test_spirv_optimizer.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_float_atomics", "unit/ext/test_spirv_float_atomics.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_glslang_spirv", "unit/ext/test_glslang_spirv.cpp", false, function()
        add_deps("lc-glslang")
    end)
    test_proj("test_spirv_ray_culling", "unit/ext/test_spirv_ray_culling.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_xir_dialect", "unit/ext/test_spirv_xir_dialect.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_handoff_boundaries", "unit/ext/test_spirv_handoff_boundaries.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_volatile_buffers", "unit/ext/test_spirv_volatile_buffers.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_aggregate_indices", "unit/ext/test_spirv_aggregate_indices.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_pointer_legalization", "unit/ext/test_spirv_pointer_legalization.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_callable_reference_handoff", "unit/ext/test_spirv_callable_reference_handoff.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_instruction_layout", "unit/ext/test_spirv_instruction_layout.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_control_flow_plan", "unit/ext/test_spirv_control_flow_plan.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_target_feature_mask", "unit/ext/test_spirv_target_feature_mask.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_target_feature_codegen", "unit/ext/test_spirv_target_feature_codegen.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_runtime_target_plan", "unit/ext/test_spirv_runtime_target_plan.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_raw_float_constants", "unit/ext/test_spirv_raw_float_constants.cpp", false, function()
        add_deps("lc-spirv")
    end)
    test_proj("test_spirv_integer_numeric_boundaries", "unit/ext/test_spirv_integer_numeric_boundaries.cpp", false, function()
        add_deps("lc-spirv")
    end)
    if has_config('lc_vk_backend_use_xir_spirv') then
        test_proj("test_spirv_bindless_xir_usage", "unit/ext/test_spirv_bindless_xir_usage.cpp", false, function()
            add_deps("lc-spirv")
        end)
    end
end
if has_config("lc_vk_backend") and
   has_config("lc_vk_backend_use_ast_llvm_spirv") then
    test_proj("test_spirv_llvm_facade", "unit/ext/test_spirv_llvm_facade.cpp", false, function()
        add_deps("lc-spirv-llvm", "spirv-tools")
    end)
end
if has_config("lc_vk_backend") then
    test_proj("test_spirv_motion_patch", "unit/ext/test_spirv_motion_patch.cpp", false, function()
        add_files("../backends/vk/spirv_motion_patch.cpp")
        add_includedirs("../backends/vk")
        add_deps("lc-volk")
    end)
    test_proj("test_vk_native_route_guard", "unit/runtime/test_vk_native_route_guard.cpp", false, function()
        if has_config('lc_vk_backend_use_xir_spirv') then
            add_defines("LUISA_TEST_VK_HAS_NATIVE_XIR_SPIRV=1")
        else
            add_defines("LUISA_TEST_VK_HAS_NATIVE_XIR_SPIRV=0")
        end
    end)
    test_proj("test_vk_sparse_residency_registry", "unit/ext/test_vk_sparse_residency_registry.cpp", false, function()
        add_includedirs("../backends/vk")
        add_files("../backends/vk/sparse_residency_registry.cpp")
        add_deps("lc-volk")
    end)
    test_proj("test_vk_shader_binary_contract", "unit/ext/test_vk_shader_binary_contract.cpp", false, function()
        add_includedirs("../backends/vk")
        add_files("../backends/vk/shader_artifact_codec.cpp")
        add_deps("lc-volk")
        if has_config('lc_vk_backend_use_xir_spirv') then
            add_deps("lc-spirv")
            add_defines("LUISA_XIR_TO_SPIRV")
        elseif has_config('lc_vk_backend_use_ast_llvm_spirv') then
            add_deps("lc-spirv")
            add_defines("LUISA_AST_LLVM_TO_SPIRV")
        end
    end)
    test_proj("test_vk_saved_argument_contract", "unit/ext/test_vk_saved_argument_contract.cpp", false, function()
        add_includedirs("../backends/vk")
    end)
    test_proj("test_vk_indirect_dispatch", "unit/ext/test_vk_indirect_dispatch.cpp", false, function()
        add_includedirs("../backends/common")
        add_includedirs("../backends/vk")
        add_deps("lc-volk")
    end)
    test_proj("test_vk_resource_barrier_contract", "unit/ext/test_vk_resource_barrier_contract.cpp", false, function()
        add_includedirs("../backends/vk")
        add_deps("lc-volk")
    end)
    test_proj("test_vk_result_contract", "unit/ext/test_vk_result_contract.cpp", false, function()
        add_includedirs("../backends/vk")
        add_files("../backends/vk/VulkanTools.cpp")
        add_deps("lc-volk")
  test_proj("test_vk_cuda_interop_texture_plan", "unit/ext/test_vk_cuda_interop_texture_plan.cpp", false, function()
      add_includedirs("../backends/vk")
  end)
  test_proj("test_vk_android_plan", "unit/ext/test_vk_android_plan.cpp", false, function()
      add_includedirs("../backends/vk")
      add_deps("lc-volk")
  end)
        add_deps("lc-volk")
    end)
    test_proj("test_vk_sparse_runtime", "unit/runtime/test_vk_sparse_runtime.cpp", false, function()
        add_deps("lc-volk")
    end)
end
test_proj("test_normal_encoding", "unit/dsl/test_normal_encoding.cpp", true)

-- unit/ast
test_proj("test_ast", "unit/ast/test_ast.cpp")
test_proj("test_ast_basic", "unit/ast/test_ast_basic.cpp")
test_proj("test_builtin_kernel", "unit/ast/test_builtin_kernel.cpp", false, function()
    add_includedirs("$(projectdir)/src/runtime")
end)
test_proj("test_manual_ast", "unit/ast/test_manual_ast.cpp")
test_proj("test_tensor_ast", "unit/ast/test_tensor_ast.cpp")
test_proj("test_tile_function_builder", "unit/ast/test_tile_function_builder.cpp")
test_proj("test_tile_kernel_dsl", "unit/ast/test_tile_kernel_dsl.cpp")
test_proj("test_tile_to_kernel", "unit/ast/test_tile_to_kernel.cpp")
test_proj("test_cooperative_vector", "unit/ast/test_cooperative_vector.cpp")
test_proj("test_tensor", "unit/ast/test_tensor.cpp")
test_proj("test_async_copy_ast", "unit/ast/test_async_copy_ast.cpp")
test_proj("test_bindless_write_usage", "unit/ast/test_bindless_write_usage.cpp")

-- unit/dsl
test_proj("test_binding_group", "unit/dsl/test_binding_group.cpp")
test_proj("test_binding_group_template", "unit/dsl/test_binding_group_template.cpp")
test_proj("test_callable", "unit/dsl/test_callable.cpp")
test_proj("test_constant", "unit/dsl/test_constant.cpp")
test_proj("test_dsl", "unit/dsl/test_dsl.cpp")
test_proj("test_dsl_sugar", "unit/dsl/test_dsl_sugar.cpp")
test_proj("test_async_copy", "unit/dsl/test_async_copy.cpp")
test_proj("test_async_copy_cuda", "unit/runtime/test_async_copy_cuda.cpp")
test_proj("test_cluster_launch_control", "unit/runtime/test_cluster_launch_control.cpp")
test_proj("test_dsl_multithread", "unit/dsl/test_dsl_multithread.cpp")
test_proj("test_soa", "unit/dsl/test_soa.cpp")
test_proj("test_soa_subview", "unit/dsl/test_soa_subview.cpp")
test_proj("test_soa_simple", "unit/dsl/test_soa_simple.cpp")
test_proj("test_device_math", "unit/dsl/test_device_math.cpp")
test_proj("test_nested_callable", "unit/dsl/test_nested_callable.cpp")
test_proj("test_calc", "unit/dsl/test_calc.cpp")
test_proj("test_dsl_matrix", "unit/dsl/test_matrix.cpp")
test_proj("test_var", "unit/dsl/test_var.cpp")
test_proj("test_8bit", "unit/dsl/test_8bit.cpp")
test_proj("test_polymorphic", "unit/dsl/test_polymorphic.cpp")
test_proj("test_dsl_autodiff", "unit/dsl/test_autodiff.cpp")

-- unit/runtime
test_proj("test_accel_build_modes", "unit/runtime/test_accel_build_modes.cpp")
test_proj("test_accel_visibility", "unit/runtime/test_accel_visibility.cpp")
test_proj("test_atomic", "unit/runtime/test_atomic.cpp")
test_proj("test_atomic_queue", "unit/runtime/test_atomic_queue.cpp")
test_proj("test_byte_buffer", "unit/runtime/test_byte_buffer.cpp")
test_proj("test_context", "unit/runtime/test_context.cpp")
test_proj("test_copy", "unit/runtime/test_copy.cpp")
test_proj("test_cpu_callable", "unit/runtime/test_cpu_callable.cpp")
test_proj("test_decoupled_look_back", "unit/runtime/test_decoupled_look_back.cpp")
test_proj("test_complex_kernel", "unit/runtime/test_complex_kernel.cpp")
test_proj("test_bindless_mip", "unit/runtime/test_bindless_mip.cpp")
test_proj("test_direct_texture_sampling", "unit/runtime/test_direct_texture_sampling.cpp")
test_proj("test_metal_codegen_regressions", "unit/runtime/test_metal_codegen_regressions.cpp")
test_proj("test_mipmap", "unit/runtime/test_mipmap.cpp")
test_proj("test_motion_instance_keyframes", "unit/runtime/test_motion_instance_keyframes.cpp")
test_proj("test_pinned_mem", "unit/runtime/test_pinned_mem.cpp")
test_proj("test_printer", "unit/runtime/test_printer.cpp")
test_proj("test_printer_custom_callback", "unit/runtime/test_printer_custom_callback.cpp")
test_proj("test_sampler", "unit/runtime/test_sampler.cpp")
test_proj("test_shared_memory", "unit/runtime/test_shared_memory.cpp")
test_proj("test_softmax", "unit/runtime/test_softmax.cpp")
-- test_tensor requires lc-tensor which is currently disabled
-- test_proj("test_tensor", "unit/runtime/test_tensor.cpp")
test_proj("test_texture_compress", "unit/runtime/test_texture_compress.cpp")
test_proj("test_pbrt_curve_parser", "unit/runtime/test_pbrt_curve_parser.cpp")
test_proj("test_texture_io", "unit/runtime/test_texture_io.cpp")
test_proj("test_timeline_event", "unit/runtime/test_timeline_event.cpp")
test_proj("test_warp", "unit/runtime/test_warp.cpp")
test_proj("test_warp_prefix_scan", "unit/runtime/test_warp_prefix_scan.cpp")
test_proj("test_warp_sparse_collectives", "unit/runtime/test_warp_sparse_collectives.cpp")
test_proj("test_hip_wave_size", "unit/runtime/test_hip_wave_size.cpp")
test_proj("test_mha_warp_reduction", "unit/runtime/test_mha_warp_reduction.cpp")
test_proj("test_ray_query_world_ray", "unit/runtime/test_ray_query_world_ray.cpp")
test_proj("test_buffer_io", "unit/runtime/test_buffer_io.cpp")
test_proj("test_buffer", "unit/runtime/test_buffer.cpp")
if has_config("lc_fallback_backend") then
    test_proj("test_fallback_shader_cache", "unit/runtime/test_fallback_shader_cache.cpp")
end
test_proj("test_out_of_range", "unit/runtime/test_out_of_range.cpp")
test_proj("test_buffer_view", "unit/runtime/test_buffer_view.cpp")
test_proj("test_device_test", "unit/runtime/test_device.cpp")
test_proj("test_external_buffer", "unit/runtime/test_external_buffer.cpp")
test_proj("test_gemm", "unit/runtime/test_gemm.cpp")
test_proj("benchmark_simd_gemm", "unit/simd/benchmark_simd_gemm.cpp")
test_proj("test_hip_codegen_arithmetic", "unit/runtime/test_hip_codegen_arithmetic.cpp")
test_proj("test_hip_curve_ray_query", "unit/runtime/test_hip_curve_ray_query.cpp")
test_proj("test_hip_motion_instance_matrix", "unit/runtime/test_hip_motion_instance_matrix.cpp")
test_proj("test_hip_motion_instance_device_ops", "unit/runtime/test_hip_motion_instance_device_ops.cpp")
test_proj("test_hip_motion_instance_srt", "unit/runtime/test_hip_motion_instance_srt.cpp")
test_proj("test_hip_motion_mesh", "unit/runtime/test_hip_motion_mesh.cpp")
test_proj("test_hip_motion_ray_query", "unit/runtime/test_hip_motion_ray_query.cpp")
test_proj("test_hip_static_motion_instance", "unit/runtime/test_hip_static_motion_instance.cpp")
test_proj("test_hip_motion_workgroup_rows", "unit/runtime/test_hip_motion_workgroup_rows.cpp")
test_proj("test_hip_ray_query_pipeline", "unit/runtime/test_hip_ray_query_pipeline.cpp")
test_proj("test_hip_signed_texture_io", "unit/runtime/test_hip_signed_texture_io.cpp")
test_proj("test_shared_mem", "unit/runtime/test_shared_mem.cpp")
test_proj("test_dsl_slp_vectorization", "unit/runtime/test_dsl_slp_vectorization.cpp")
test_proj("test_dsl_fuse_buffer_reads", "unit/runtime/test_dsl_fuse_buffer_reads.cpp")
test_proj("test_dsl_indvar_strength_reduce", "unit/runtime/test_dsl_indvar_strength_reduce.cpp")
test_proj("test_dsl_xir_optimize_vk", "unit/runtime/test_dsl_xir_optimize_vk.cpp")

-- unit/coro
test_proj("test_coro_scheduler_base", "unit/coro/test_coro_scheduler_base.cpp")
test_proj("test_coro_multisplit", "unit/coro/test_coro_multisplit.cpp")
test_proj("test_coro_compaction", "unit/coro/test_coro_compaction.cpp")
test_proj("test_coro_radix_sort", "unit/coro/test_coro_radix_sort.cpp")

-- unit/xir
if has_config("lc_enable_xir") then
    local function coro_xir_test_proj(name, source)
        test_proj(name, source, false, function()
            add_defines("LUISA_ENABLE_XIR")
            add_deps("lc-coro")
        end)
    end
    test_proj("test_ast_to_xir", "unit/xir/test_ast_to_xir.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_passes", "unit/xir/test_xir_passes.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_aggregate_field_bitmask", "unit/xir/test_xir_aggregate_field_bitmask.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_alias_analysis", "unit/xir/test_xir_pass_alias_analysis.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_core_analyses", "unit/xir/test_xir_pass_core_analyses.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_pointer_usage", "unit/xir/test_xir_pass_pointer_usage.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_scalar_evolution", "unit/xir/test_xir_pass_scalar_evolution.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_unused_callable_removal", "unit/xir/test_xir_pass_unused_callable_removal.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_post_dom_tree", "unit/xir/test_xir_pass_post_dom_tree.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_autodiff_cfg", "unit/xir/test_xir_pass_autodiff_cfg.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_licm", "unit/xir/test_xir_pass_licm.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_indvar_simplify", "unit/xir/test_xir_pass_indvar_simplify.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_loop_rotation", "unit/xir/test_xir_pass_loop_rotation.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_loop_fusion", "unit/xir/test_xir_pass_loop_fusion.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_loop_vectorization", "unit/xir/test_xir_pass_loop_vectorization.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_sccp", "unit/xir/test_xir_pass_sccp.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_slp_vectorization", "unit/xir/test_xir_pass_slp_vectorization.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir2ast_translators", "unit/xir/test_xir2ast_translators.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_restructure_cfg", "unit/xir/test_xir_pass_restructure_cfg.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_module", "unit/xir/test_xir_module.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_builder", "unit/xir/test_xir_builder.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_verifier", "unit/xir/test_xir_verifier.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_translators", "unit/xir/test_xir_translators.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_interchange", "unit/xir/test_xir_interchange.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_lower_break_continue", "unit/xir/test_xir_pass_lower_break_continue.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_destructure_cfg", "unit/xir/test_xir_pass_destructure_cfg.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_simplify_cfg", "unit/xir/test_xir_pass_simplify_cfg.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_early_cse", "unit/xir/test_xir_pass_early_cse.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_lower_ray_query_to_pipeline", "unit/xir/test_xir_pass_lower_ray_query_to_pipeline.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_reconstruct_ray_query_loop", "unit/xir/test_xir_pass_reconstruct_ray_query_loop.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_fuse_consecutive_buffer_reads", "unit/xir/test_xir_pass_fuse_consecutive_buffer_reads.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_convergence_region", "unit/xir/test_xir_pass_convergence_region.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_early_return_elimination", "unit/xir/test_xir_pass_early_return_elimination.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_pipeline", "unit/xir/test_xir_pass_pipeline.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
    test_proj("test_xir_pass_mutation_safety", "unit/xir/test_xir_pass_mutation_safety.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)

    coro_xir_test_proj("test_coro_graph", "unit/coro/test_coro_graph.cpp")
    coro_xir_test_proj("test_coro_state_machine", "unit/coro/test_coro_state_machine.cpp")
    coro_xir_test_proj("test_coro_persistent", "unit/coro/test_coro_persistent.cpp")
    coro_xir_test_proj("test_coro_persistent_opt", "unit/coro/test_coro_persistent_opt.cpp")
    coro_xir_test_proj("test_coro_persistent_integration", "unit/coro/test_coro_persistent_integration.cpp")
    coro_xir_test_proj("test_coro_soa_layout", "unit/coro/test_coro_soa_layout.cpp")
    coro_xir_test_proj("test_coro_wavefront", "unit/coro/test_coro_wavefront.cpp")
    coro_xir_test_proj("test_coro_all_schedulers", "unit/coro/test_coro_all_schedulers.cpp")
    coro_xir_test_proj("test_coro_wavefront_integration", "unit/coro/test_coro_wavefront_integration.cpp")
    coro_xir_test_proj("test_coro_pipeline_1suspend", "unit/coro/test_coro_pipeline_1suspend.cpp")
    coro_xir_test_proj("test_coro_pipeline_3suspend", "unit/coro/test_coro_pipeline_3suspend.cpp")
    coro_xir_test_proj("test_xir_coro_cfg_distill", "unit/xir/test_coro_cfg_distill.cpp")
    coro_xir_test_proj("test_xir_coro_cfg_dataflow", "unit/xir/test_coro_cfg_dataflow.cpp")
    coro_xir_test_proj("test_xir_pass_coro_alloca_scope", "unit/xir/test_xir_pass_coro_alloca_scope.cpp")
    coro_xir_test_proj("test_xir_coro_materialize", "unit/xir/test_coro_materialize.cpp")
    coro_xir_test_proj("test_coro_dead_field", "unit/xir/test_coro_dead_field.cpp")
    coro_xir_test_proj("test_coro_frame_size", "unit/xir/test_coro_frame_size.cpp")
    coro_xir_test_proj("test_xir_coro_reg2mem", "unit/xir/test_coro_reg2mem.cpp")
    coro_xir_test_proj("test_xir_coro_split", "unit/xir/test_coro_split.cpp")
    coro_xir_test_proj("test_coro_restructure_validation", "unit/xir/test_coro_restructure_validation.cpp")
    coro_xir_test_proj("test_xir_coro_xir2ast", "unit/xir/test_coro_xir2ast.cpp")
    coro_xir_test_proj("test_xir_coro_pipeline", "unit/xir/test_coro_pipeline.cpp")
    coro_xir_test_proj("test_coro_frame_desc", "unit/dsl/test_coro_frame_desc.cpp")
    coro_xir_test_proj("test_coro_frame_runtime", "unit/dsl/test_coro_frame_runtime.cpp")
    coro_xir_test_proj("test_coro_compile_trigger", "unit/dsl/test_coro_compile_trigger.cpp")
    coro_xir_test_proj("test_coro_func", "unit/dsl/test_coro_func.cpp")
    coro_xir_test_proj("test_coro_suspend", "unit/dsl/test_coro_suspend.cpp")
end

-- integration/runtime
test_proj("test_aot", "integration/runtime/test_aot.cpp", true)
test_proj("test_device_debugger", "integration/runtime/test_device_debugger.cpp")
test_proj("test_dstorage_decompression", "integration/runtime/test_dstorage_decompression.cpp", true)
test_proj("test_procedural_callable", "integration/runtime/test_procedural_callable.cpp")
test_proj("test_rtx", "integration/runtime/test_rtx.cpp")
if has_config("lc_enable_osl") then
    test_proj("test_oso_parser", "integration/runtime/test_oso_parser.cpp", false, function()
        add_deps("lc-osl")
    end)
end

test_proj("test_bindless", "integration/runtime/test_bindless.cpp", true)
test_proj("test_bindless_buffer", "integration/runtime/test_bindless_buffer.cpp", true)
test_proj("test_curve", "integration/runtime/test_curve.cpp", true)
test_proj("test_curve_pbrt", "integration/runtime/test_curve_pbrt.cpp", true)
test_proj("test_curve_pbrt_diffuse", "integration/runtime/test_curve_pbrt_diffuse.cpp", true)
test_proj("test_denoiser", "integration/runtime/test_denoiser.cpp", true)
test_proj("test_indirect", "integration/runtime/test_indirect.cpp", true)
test_proj("test_indirect_rtx", "integration/runtime/test_indirect_rtx.cpp", true)
test_proj("test_motion_blur", "integration/runtime/test_motion_blur.cpp", true)
test_proj("test_motion_blur_vk", "integration/runtime/test_motion_blur_vk.cpp", true)
if has_config("lc_vk_backend") and
   has_config("lc_vk_backend_use_xir_spirv") then
    test_proj("test_vk_shader_cache", "unit/runtime/test_vk_shader_cache.cpp")
    test_proj("test_vk_spirv_codegen_path", "unit/runtime/test_vk_spirv_codegen_path.cpp", false, function()
        add_includedirs("../backends/vk")
        add_includedirs("../backends/common")
        add_deps("lc-spirv", "lc-volk")
        add_cxxflags("/bigobj", {tools = "cl"})
    end)
end
test_proj("test_mesh", "integration/runtime/motion_blur/test_mesh.cpp", true)
test_proj("test_mesh_2", "integration/runtime/motion_blur/test_mesh_2.cpp", true)
test_proj("test_mesh_3", "integration/runtime/motion_blur/test_mesh_3.cpp", true)
test_proj("test_mesh_4", "integration/runtime/motion_blur/test_mesh_4.cpp", true)
test_proj("test_native_include", "integration/runtime/test_native_include.cpp", true)
test_proj("test_present", "integration/runtime/test_present.cpp", true)
test_proj("test_runtime", "integration/runtime/test_runtime.cpp", true)
test_proj("test_select_device", "integration/runtime/test_select_device.cpp", true)
test_proj("test_texture3d", "integration/runtime/test_texture3d.cpp", true)
test_proj("test_transient_resource", "integration/runtime/test_transient_resource.cpp", true, function()
    add_files("integration/runtime/transient_resource_device/*.cpp")
end)

-- integration/runtime: CUDA-only tests
if has_config("lc_cuda_backend") then
    test_proj("test_cuda_graph", "integration/runtime/test_cuda_graph.cpp")
end

-- integration/runtime: DX-only tests
if has_config("lc_dx_backend") then
    test_proj("test_raster", "integration/runtime/test_raster.cpp", true)
    test_proj("test_memory_compact", "integration/runtime/test_memory_compact.cpp", false, function()
        if has_config("lc_vk_backend") then
            add_deps("lc-volk")
        end
    end)
    -- test_work_graph disabled: work_graph headers not found
    -- test_proj("test_work_graph", "integration/runtime/test_work_graph.cpp")
end

if has_config("lc_enable_xir") then
    test_proj("test_xir2ast_roundtrip", "integration/xir/test_xir2ast_roundtrip.cpp", false, function()
        add_defines("LUISA_ENABLE_XIR")
    end)
end

-- unit/dsl: standalone GPU tests
test_proj("test_dsl_mathematic", "unit/dsl/test_dsl_mathematic.cpp")

-- unit/runtime: FP4/FP8 quantization tests
test_proj("test_fp4", "unit/runtime/test_fp4.cpp")
test_proj("test_fp4_quantization", "unit/runtime/test_fp4_quantization.cpp")
test_proj("test_fp8", "unit/runtime/test_fp8.cpp")
test_proj("test_fp8_quantization", "unit/runtime/test_fp8_quantization.cpp")

-- standalone CUDA tensor dispatch example: raw CUDA runtime + driver API with
-- runtime NVRTC JIT (kernel source is a C++ raw string; no .cu compilation).
-- Deliberately depends only on lc-core + lc-cuda-backend-base (NOT lc-runtime,
-- lc-dsl, lc-vstl, or lc-backends-dummy) so it stays a host-only example.
if has_config("lc_cuda_backend") then
    target("test_cuda_tensor_dispatch")
    _config_project({project_kind = "binary"})
    add_files("cuda/test_cuda_tensor_dispatch.cpp")
    add_includedirs("./", "./common")
    add_deps("lc-core", "lc-cuda-backend-base")
    add_links("cuda", "cudart", "nvrtc")
    on_load(function(target)
        local cuda_path = os.getenv("CUDA_PATH")
        if cuda_path then
            local forward = (cuda_path:gsub("\\", "/"))
            target:add("defines", string.format('LUISA_TEST_CUDA_PATH="%s"', forward))
            target:add("runenvs", "PATH", path.join(cuda_path, "bin"))
        end
    end)
    target_end()
end
