def make_float4x4(*args, **kwargs): ...
def make_bool3(*args, **kwargs): ...
def atan(*args, **kwargs): ...
def trunc(*args, **kwargs): ...
def floor(*args, **kwargs): ...
def log_level_info(*args, **kwargs): ...
def none(*args, **kwargs): ...
def min(*args, **kwargs): ...
def log_level_warning(*args, **kwargs): ...
def make_float2x2(*args, **kwargs): ...
def max(*args, **kwargs): ...
def sqrt(*args, **kwargs): ...
def thread_id(*args, **kwargs): ...
def abs(*args, **kwargs): ...
def make_uint3(*args, **kwargs): ...
def clz(*args, **kwargs): ...
def any(*args, **kwargs): ...
def isnan(*args, **kwargs): ...
def log_level_error(*args, **kwargs): ...
def make_float2(*args, **kwargs): ...
def exp2(*args, **kwargs): ...
def clamp(*args, **kwargs): ...
def ceil(*args, **kwargs): ...
def log(*args, **kwargs): ...
def builder(*args, **kwargs): ...
def length(*args, **kwargs): ...
def sign(*args, **kwargs): ...
def isinf(*args, **kwargs): ...
def pixel_storage_size(*args, **kwargs): ...
def radians(*args, **kwargs): ...
def saturate(*args, **kwargs): ...
def pow(*args, **kwargs): ...
def length_squared(*args, **kwargs): ...
def ite(*args, **kwargs): ...
def make_int2(*args, **kwargs): ...
def make_float3(*args, **kwargs): ...
def atanh(*args, **kwargs): ...
def determinant(*args, **kwargs): ...
def fma(*args, **kwargs): ...
def inverse(*args, **kwargs): ...
def log10(*args, **kwargs): ...
def make_float4(*args, **kwargs): ...
def distance(*args, **kwargs): ...
def exp(*args, **kwargs): ...
def cos(*args, **kwargs): ...
def normalize(*args, **kwargs): ...
def dispatch_id(*args, **kwargs): ...
def acosh(*args, **kwargs): ...
def sin(*args, **kwargs): ...
def cross(*args, **kwargs): ...
def rsqrt(*args, **kwargs): ...
def tanh(*args, **kwargs): ...
def fract(*args, **kwargs): ...
def distance_squared(*args, **kwargs): ...
def fmod(*args, **kwargs): ...
def all(*args, **kwargs): ...
def degrees(*args, **kwargs): ...
def make_uint4(*args, **kwargs): ...
def exp10(*args, **kwargs): ...
def pixel_storage_channel_count(*args, **kwargs): ...
def smoothstep(*args, **kwargs): ...
def make_bool4(*args, **kwargs): ...
def ctz(*args, **kwargs): ...
def dot(*args, **kwargs): ...
def round(*args, **kwargs): ...
def atan2(*args, **kwargs): ...
def step(*args, **kwargs): ...
def transpose(*args, **kwargs): ...
def make_uint2(*args, **kwargs): ...
def make_float3x3(*args, **kwargs): ...
def select(*args, **kwargs): ...
def popcount(*args, **kwargs): ...
def block_id(*args, **kwargs): ...
def set_block_size(*args, **kwargs): ...
def tan(*args, **kwargs): ...
def sinh(*args, **kwargs): ...
def pixel_storage_to_format_int(*args, **kwargs): ...
def faceforward(*args, **kwargs): ...
def log_level_verbose(*args, **kwargs): ...
def log2(*args, **kwargs): ...
def pixel_storage_to_format_float(*args, **kwargs): ...
def make_bool2(*args, **kwargs): ...
def make_int3(*args, **kwargs): ...
def reverse(*args, **kwargs): ...
def to_bytes(*args, **kwargs): ...
def mod(*args, **kwargs): ...
def acos(*args, **kwargs): ...
def lerp(*args, **kwargs): ...
def make_int4(*args, **kwargs): ...
def cosh(*args, **kwargs): ...
def copysign(*args, **kwargs): ...
def dispatch_size(*args, **kwargs): ...
class float2x2:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
class float3x3:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
class float4x4:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def w(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def xw(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def yw(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def zw(self): ...
    @property
    def wx(self): ...
    @property
    def wy(self): ...
    @property
    def wz(self): ...
    @property
    def ww(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xxw(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xyw(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def xzw(self): ...
    @property
    def xwx(self): ...
    @property
    def xwy(self): ...
    @property
    def xwz(self): ...
    @property
    def xww(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yxw(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yyw(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def yzw(self): ...
    @property
    def ywx(self): ...
    @property
    def ywy(self): ...
    @property
    def ywz(self): ...
    @property
    def yww(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zxw(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zyw(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def zzw(self): ...
    @property
    def zwx(self): ...
    @property
    def zwy(self): ...
    @property
    def zwz(self): ...
    @property
    def zww(self): ...
    @property
    def wxx(self): ...
    @property
    def wxy(self): ...
    @property
    def wxz(self): ...
    @property
    def wxw(self): ...
    @property
    def wyx(self): ...
    @property
    def wyy(self): ...
    @property
    def wyz(self): ...
    @property
    def wyw(self): ...
    @property
    def wzx(self): ...
    @property
    def wzy(self): ...
    @property
    def wzz(self): ...
    @property
    def wzw(self): ...
    @property
    def wwx(self): ...
    @property
    def wwy(self): ...
    @property
    def wwz(self): ...
    @property
    def www(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxxw(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxyw(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xxzw(self): ...
    @property
    def xxwx(self): ...
    @property
    def xxwy(self): ...
    @property
    def xxwz(self): ...
    @property
    def xxww(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyxw(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyyw(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xyzw(self): ...
    @property
    def xywx(self): ...
    @property
    def xywy(self): ...
    @property
    def xywz(self): ...
    @property
    def xyww(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzxw(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzyw(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def xzzw(self): ...
    @property
    def xzwx(self): ...
    @property
    def xzwy(self): ...
    @property
    def xzwz(self): ...
    @property
    def xzww(self): ...
    @property
    def xwxx(self): ...
    @property
    def xwxy(self): ...
    @property
    def xwxz(self): ...
    @property
    def xwxw(self): ...
    @property
    def xwyx(self): ...
    @property
    def xwyy(self): ...
    @property
    def xwyz(self): ...
    @property
    def xwyw(self): ...
    @property
    def xwzx(self): ...
    @property
    def xwzy(self): ...
    @property
    def xwzz(self): ...
    @property
    def xwzw(self): ...
    @property
    def xwwx(self): ...
    @property
    def xwwy(self): ...
    @property
    def xwwz(self): ...
    @property
    def xwww(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxxw(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxyw(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yxzw(self): ...
    @property
    def yxwx(self): ...
    @property
    def yxwy(self): ...
    @property
    def yxwz(self): ...
    @property
    def yxww(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyxw(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyyw(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yyzw(self): ...
    @property
    def yywx(self): ...
    @property
    def yywy(self): ...
    @property
    def yywz(self): ...
    @property
    def yyww(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzxw(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzyw(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def yzzw(self): ...
    @property
    def yzwx(self): ...
    @property
    def yzwy(self): ...
    @property
    def yzwz(self): ...
    @property
    def yzww(self): ...
    @property
    def ywxx(self): ...
    @property
    def ywxy(self): ...
    @property
    def ywxz(self): ...
    @property
    def ywxw(self): ...
    @property
    def ywyx(self): ...
    @property
    def ywyy(self): ...
    @property
    def ywyz(self): ...
    @property
    def ywyw(self): ...
    @property
    def ywzx(self): ...
    @property
    def ywzy(self): ...
    @property
    def ywzz(self): ...
    @property
    def ywzw(self): ...
    @property
    def ywwx(self): ...
    @property
    def ywwy(self): ...
    @property
    def ywwz(self): ...
    @property
    def ywww(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxxw(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxyw(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zxzw(self): ...
    @property
    def zxwx(self): ...
    @property
    def zxwy(self): ...
    @property
    def zxwz(self): ...
    @property
    def zxww(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyxw(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyyw(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zyzw(self): ...
    @property
    def zywx(self): ...
    @property
    def zywy(self): ...
    @property
    def zywz(self): ...
    @property
    def zyww(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzxw(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzyw(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
    @property
    def zzzw(self): ...
    @property
    def zzwx(self): ...
    @property
    def zzwy(self): ...
    @property
    def zzwz(self): ...
    @property
    def zzww(self): ...
    @property
    def zwxx(self): ...
    @property
    def zwxy(self): ...
    @property
    def zwxz(self): ...
    @property
    def zwxw(self): ...
    @property
    def zwyx(self): ...
    @property
    def zwyy(self): ...
    @property
    def zwyz(self): ...
    @property
    def zwyw(self): ...
    @property
    def zwzx(self): ...
    @property
    def zwzy(self): ...
    @property
    def zwzz(self): ...
    @property
    def zwzw(self): ...
    @property
    def zwwx(self): ...
    @property
    def zwwy(self): ...
    @property
    def zwwz(self): ...
    @property
    def zwww(self): ...
    @property
    def wxxx(self): ...
    @property
    def wxxy(self): ...
    @property
    def wxxz(self): ...
    @property
    def wxxw(self): ...
    @property
    def wxyx(self): ...
    @property
    def wxyy(self): ...
    @property
    def wxyz(self): ...
    @property
    def wxyw(self): ...
    @property
    def wxzx(self): ...
    @property
    def wxzy(self): ...
    @property
    def wxzz(self): ...
    @property
    def wxzw(self): ...
    @property
    def wxwx(self): ...
    @property
    def wxwy(self): ...
    @property
    def wxwz(self): ...
    @property
    def wxww(self): ...
    @property
    def wyxx(self): ...
    @property
    def wyxy(self): ...
    @property
    def wyxz(self): ...
    @property
    def wyxw(self): ...
    @property
    def wyyx(self): ...
    @property
    def wyyy(self): ...
    @property
    def wyyz(self): ...
    @property
    def wyyw(self): ...
    @property
    def wyzx(self): ...
    @property
    def wyzy(self): ...
    @property
    def wyzz(self): ...
    @property
    def wyzw(self): ...
    @property
    def wywx(self): ...
    @property
    def wywy(self): ...
    @property
    def wywz(self): ...
    @property
    def wyww(self): ...
    @property
    def wzxx(self): ...
    @property
    def wzxy(self): ...
    @property
    def wzxz(self): ...
    @property
    def wzxw(self): ...
    @property
    def wzyx(self): ...
    @property
    def wzyy(self): ...
    @property
    def wzyz(self): ...
    @property
    def wzyw(self): ...
    @property
    def wzzx(self): ...
    @property
    def wzzy(self): ...
    @property
    def wzzz(self): ...
    @property
    def wzzw(self): ...
    @property
    def wzwx(self): ...
    @property
    def wzwy(self): ...
    @property
    def wzwz(self): ...
    @property
    def wzww(self): ...
    @property
    def wwxx(self): ...
    @property
    def wwxy(self): ...
    @property
    def wwxz(self): ...
    @property
    def wwxw(self): ...
    @property
    def wwyx(self): ...
    @property
    def wwyy(self): ...
    @property
    def wwyz(self): ...
    @property
    def wwyw(self): ...
    @property
    def wwzx(self): ...
    @property
    def wwzy(self): ...
    @property
    def wwzz(self): ...
    @property
    def wwzw(self): ...
    @property
    def wwwx(self): ...
    @property
    def wwwy(self): ...
    @property
    def wwwz(self): ...
    @property
    def wwww(self): ...
class int2:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
class int3:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
class int4:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def w(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def xw(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def yw(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def zw(self): ...
    @property
    def wx(self): ...
    @property
    def wy(self): ...
    @property
    def wz(self): ...
    @property
    def ww(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xxw(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xyw(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def xzw(self): ...
    @property
    def xwx(self): ...
    @property
    def xwy(self): ...
    @property
    def xwz(self): ...
    @property
    def xww(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yxw(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yyw(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def yzw(self): ...
    @property
    def ywx(self): ...
    @property
    def ywy(self): ...
    @property
    def ywz(self): ...
    @property
    def yww(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zxw(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zyw(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def zzw(self): ...
    @property
    def zwx(self): ...
    @property
    def zwy(self): ...
    @property
    def zwz(self): ...
    @property
    def zww(self): ...
    @property
    def wxx(self): ...
    @property
    def wxy(self): ...
    @property
    def wxz(self): ...
    @property
    def wxw(self): ...
    @property
    def wyx(self): ...
    @property
    def wyy(self): ...
    @property
    def wyz(self): ...
    @property
    def wyw(self): ...
    @property
    def wzx(self): ...
    @property
    def wzy(self): ...
    @property
    def wzz(self): ...
    @property
    def wzw(self): ...
    @property
    def wwx(self): ...
    @property
    def wwy(self): ...
    @property
    def wwz(self): ...
    @property
    def www(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxxw(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxyw(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xxzw(self): ...
    @property
    def xxwx(self): ...
    @property
    def xxwy(self): ...
    @property
    def xxwz(self): ...
    @property
    def xxww(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyxw(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyyw(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xyzw(self): ...
    @property
    def xywx(self): ...
    @property
    def xywy(self): ...
    @property
    def xywz(self): ...
    @property
    def xyww(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzxw(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzyw(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def xzzw(self): ...
    @property
    def xzwx(self): ...
    @property
    def xzwy(self): ...
    @property
    def xzwz(self): ...
    @property
    def xzww(self): ...
    @property
    def xwxx(self): ...
    @property
    def xwxy(self): ...
    @property
    def xwxz(self): ...
    @property
    def xwxw(self): ...
    @property
    def xwyx(self): ...
    @property
    def xwyy(self): ...
    @property
    def xwyz(self): ...
    @property
    def xwyw(self): ...
    @property
    def xwzx(self): ...
    @property
    def xwzy(self): ...
    @property
    def xwzz(self): ...
    @property
    def xwzw(self): ...
    @property
    def xwwx(self): ...
    @property
    def xwwy(self): ...
    @property
    def xwwz(self): ...
    @property
    def xwww(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxxw(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxyw(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yxzw(self): ...
    @property
    def yxwx(self): ...
    @property
    def yxwy(self): ...
    @property
    def yxwz(self): ...
    @property
    def yxww(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyxw(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyyw(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yyzw(self): ...
    @property
    def yywx(self): ...
    @property
    def yywy(self): ...
    @property
    def yywz(self): ...
    @property
    def yyww(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzxw(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzyw(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def yzzw(self): ...
    @property
    def yzwx(self): ...
    @property
    def yzwy(self): ...
    @property
    def yzwz(self): ...
    @property
    def yzww(self): ...
    @property
    def ywxx(self): ...
    @property
    def ywxy(self): ...
    @property
    def ywxz(self): ...
    @property
    def ywxw(self): ...
    @property
    def ywyx(self): ...
    @property
    def ywyy(self): ...
    @property
    def ywyz(self): ...
    @property
    def ywyw(self): ...
    @property
    def ywzx(self): ...
    @property
    def ywzy(self): ...
    @property
    def ywzz(self): ...
    @property
    def ywzw(self): ...
    @property
    def ywwx(self): ...
    @property
    def ywwy(self): ...
    @property
    def ywwz(self): ...
    @property
    def ywww(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxxw(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxyw(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zxzw(self): ...
    @property
    def zxwx(self): ...
    @property
    def zxwy(self): ...
    @property
    def zxwz(self): ...
    @property
    def zxww(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyxw(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyyw(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zyzw(self): ...
    @property
    def zywx(self): ...
    @property
    def zywy(self): ...
    @property
    def zywz(self): ...
    @property
    def zyww(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzxw(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzyw(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
    @property
    def zzzw(self): ...
    @property
    def zzwx(self): ...
    @property
    def zzwy(self): ...
    @property
    def zzwz(self): ...
    @property
    def zzww(self): ...
    @property
    def zwxx(self): ...
    @property
    def zwxy(self): ...
    @property
    def zwxz(self): ...
    @property
    def zwxw(self): ...
    @property
    def zwyx(self): ...
    @property
    def zwyy(self): ...
    @property
    def zwyz(self): ...
    @property
    def zwyw(self): ...
    @property
    def zwzx(self): ...
    @property
    def zwzy(self): ...
    @property
    def zwzz(self): ...
    @property
    def zwzw(self): ...
    @property
    def zwwx(self): ...
    @property
    def zwwy(self): ...
    @property
    def zwwz(self): ...
    @property
    def zwww(self): ...
    @property
    def wxxx(self): ...
    @property
    def wxxy(self): ...
    @property
    def wxxz(self): ...
    @property
    def wxxw(self): ...
    @property
    def wxyx(self): ...
    @property
    def wxyy(self): ...
    @property
    def wxyz(self): ...
    @property
    def wxyw(self): ...
    @property
    def wxzx(self): ...
    @property
    def wxzy(self): ...
    @property
    def wxzz(self): ...
    @property
    def wxzw(self): ...
    @property
    def wxwx(self): ...
    @property
    def wxwy(self): ...
    @property
    def wxwz(self): ...
    @property
    def wxww(self): ...
    @property
    def wyxx(self): ...
    @property
    def wyxy(self): ...
    @property
    def wyxz(self): ...
    @property
    def wyxw(self): ...
    @property
    def wyyx(self): ...
    @property
    def wyyy(self): ...
    @property
    def wyyz(self): ...
    @property
    def wyyw(self): ...
    @property
    def wyzx(self): ...
    @property
    def wyzy(self): ...
    @property
    def wyzz(self): ...
    @property
    def wyzw(self): ...
    @property
    def wywx(self): ...
    @property
    def wywy(self): ...
    @property
    def wywz(self): ...
    @property
    def wyww(self): ...
    @property
    def wzxx(self): ...
    @property
    def wzxy(self): ...
    @property
    def wzxz(self): ...
    @property
    def wzxw(self): ...
    @property
    def wzyx(self): ...
    @property
    def wzyy(self): ...
    @property
    def wzyz(self): ...
    @property
    def wzyw(self): ...
    @property
    def wzzx(self): ...
    @property
    def wzzy(self): ...
    @property
    def wzzz(self): ...
    @property
    def wzzw(self): ...
    @property
    def wzwx(self): ...
    @property
    def wzwy(self): ...
    @property
    def wzwz(self): ...
    @property
    def wzww(self): ...
    @property
    def wwxx(self): ...
    @property
    def wwxy(self): ...
    @property
    def wwxz(self): ...
    @property
    def wwxw(self): ...
    @property
    def wwyx(self): ...
    @property
    def wwyy(self): ...
    @property
    def wwyz(self): ...
    @property
    def wwyw(self): ...
    @property
    def wwzx(self): ...
    @property
    def wwzy(self): ...
    @property
    def wwzz(self): ...
    @property
    def wwzw(self): ...
    @property
    def wwwx(self): ...
    @property
    def wwwy(self): ...
    @property
    def wwwz(self): ...
    @property
    def wwww(self): ...
class uint2:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
class uint3:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
class uint4:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def w(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def xw(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def yw(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def zw(self): ...
    @property
    def wx(self): ...
    @property
    def wy(self): ...
    @property
    def wz(self): ...
    @property
    def ww(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xxw(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xyw(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def xzw(self): ...
    @property
    def xwx(self): ...
    @property
    def xwy(self): ...
    @property
    def xwz(self): ...
    @property
    def xww(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yxw(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yyw(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def yzw(self): ...
    @property
    def ywx(self): ...
    @property
    def ywy(self): ...
    @property
    def ywz(self): ...
    @property
    def yww(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zxw(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zyw(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def zzw(self): ...
    @property
    def zwx(self): ...
    @property
    def zwy(self): ...
    @property
    def zwz(self): ...
    @property
    def zww(self): ...
    @property
    def wxx(self): ...
    @property
    def wxy(self): ...
    @property
    def wxz(self): ...
    @property
    def wxw(self): ...
    @property
    def wyx(self): ...
    @property
    def wyy(self): ...
    @property
    def wyz(self): ...
    @property
    def wyw(self): ...
    @property
    def wzx(self): ...
    @property
    def wzy(self): ...
    @property
    def wzz(self): ...
    @property
    def wzw(self): ...
    @property
    def wwx(self): ...
    @property
    def wwy(self): ...
    @property
    def wwz(self): ...
    @property
    def www(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxxw(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxyw(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xxzw(self): ...
    @property
    def xxwx(self): ...
    @property
    def xxwy(self): ...
    @property
    def xxwz(self): ...
    @property
    def xxww(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyxw(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyyw(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xyzw(self): ...
    @property
    def xywx(self): ...
    @property
    def xywy(self): ...
    @property
    def xywz(self): ...
    @property
    def xyww(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzxw(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzyw(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def xzzw(self): ...
    @property
    def xzwx(self): ...
    @property
    def xzwy(self): ...
    @property
    def xzwz(self): ...
    @property
    def xzww(self): ...
    @property
    def xwxx(self): ...
    @property
    def xwxy(self): ...
    @property
    def xwxz(self): ...
    @property
    def xwxw(self): ...
    @property
    def xwyx(self): ...
    @property
    def xwyy(self): ...
    @property
    def xwyz(self): ...
    @property
    def xwyw(self): ...
    @property
    def xwzx(self): ...
    @property
    def xwzy(self): ...
    @property
    def xwzz(self): ...
    @property
    def xwzw(self): ...
    @property
    def xwwx(self): ...
    @property
    def xwwy(self): ...
    @property
    def xwwz(self): ...
    @property
    def xwww(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxxw(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxyw(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yxzw(self): ...
    @property
    def yxwx(self): ...
    @property
    def yxwy(self): ...
    @property
    def yxwz(self): ...
    @property
    def yxww(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyxw(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyyw(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yyzw(self): ...
    @property
    def yywx(self): ...
    @property
    def yywy(self): ...
    @property
    def yywz(self): ...
    @property
    def yyww(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzxw(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzyw(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def yzzw(self): ...
    @property
    def yzwx(self): ...
    @property
    def yzwy(self): ...
    @property
    def yzwz(self): ...
    @property
    def yzww(self): ...
    @property
    def ywxx(self): ...
    @property
    def ywxy(self): ...
    @property
    def ywxz(self): ...
    @property
    def ywxw(self): ...
    @property
    def ywyx(self): ...
    @property
    def ywyy(self): ...
    @property
    def ywyz(self): ...
    @property
    def ywyw(self): ...
    @property
    def ywzx(self): ...
    @property
    def ywzy(self): ...
    @property
    def ywzz(self): ...
    @property
    def ywzw(self): ...
    @property
    def ywwx(self): ...
    @property
    def ywwy(self): ...
    @property
    def ywwz(self): ...
    @property
    def ywww(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxxw(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxyw(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zxzw(self): ...
    @property
    def zxwx(self): ...
    @property
    def zxwy(self): ...
    @property
    def zxwz(self): ...
    @property
    def zxww(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyxw(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyyw(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zyzw(self): ...
    @property
    def zywx(self): ...
    @property
    def zywy(self): ...
    @property
    def zywz(self): ...
    @property
    def zyww(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzxw(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzyw(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
    @property
    def zzzw(self): ...
    @property
    def zzwx(self): ...
    @property
    def zzwy(self): ...
    @property
    def zzwz(self): ...
    @property
    def zzww(self): ...
    @property
    def zwxx(self): ...
    @property
    def zwxy(self): ...
    @property
    def zwxz(self): ...
    @property
    def zwxw(self): ...
    @property
    def zwyx(self): ...
    @property
    def zwyy(self): ...
    @property
    def zwyz(self): ...
    @property
    def zwyw(self): ...
    @property
    def zwzx(self): ...
    @property
    def zwzy(self): ...
    @property
    def zwzz(self): ...
    @property
    def zwzw(self): ...
    @property
    def zwwx(self): ...
    @property
    def zwwy(self): ...
    @property
    def zwwz(self): ...
    @property
    def zwww(self): ...
    @property
    def wxxx(self): ...
    @property
    def wxxy(self): ...
    @property
    def wxxz(self): ...
    @property
    def wxxw(self): ...
    @property
    def wxyx(self): ...
    @property
    def wxyy(self): ...
    @property
    def wxyz(self): ...
    @property
    def wxyw(self): ...
    @property
    def wxzx(self): ...
    @property
    def wxzy(self): ...
    @property
    def wxzz(self): ...
    @property
    def wxzw(self): ...
    @property
    def wxwx(self): ...
    @property
    def wxwy(self): ...
    @property
    def wxwz(self): ...
    @property
    def wxww(self): ...
    @property
    def wyxx(self): ...
    @property
    def wyxy(self): ...
    @property
    def wyxz(self): ...
    @property
    def wyxw(self): ...
    @property
    def wyyx(self): ...
    @property
    def wyyy(self): ...
    @property
    def wyyz(self): ...
    @property
    def wyyw(self): ...
    @property
    def wyzx(self): ...
    @property
    def wyzy(self): ...
    @property
    def wyzz(self): ...
    @property
    def wyzw(self): ...
    @property
    def wywx(self): ...
    @property
    def wywy(self): ...
    @property
    def wywz(self): ...
    @property
    def wyww(self): ...
    @property
    def wzxx(self): ...
    @property
    def wzxy(self): ...
    @property
    def wzxz(self): ...
    @property
    def wzxw(self): ...
    @property
    def wzyx(self): ...
    @property
    def wzyy(self): ...
    @property
    def wzyz(self): ...
    @property
    def wzyw(self): ...
    @property
    def wzzx(self): ...
    @property
    def wzzy(self): ...
    @property
    def wzzz(self): ...
    @property
    def wzzw(self): ...
    @property
    def wzwx(self): ...
    @property
    def wzwy(self): ...
    @property
    def wzwz(self): ...
    @property
    def wzww(self): ...
    @property
    def wwxx(self): ...
    @property
    def wwxy(self): ...
    @property
    def wwxz(self): ...
    @property
    def wwxw(self): ...
    @property
    def wwyx(self): ...
    @property
    def wwyy(self): ...
    @property
    def wwyz(self): ...
    @property
    def wwyw(self): ...
    @property
    def wwzx(self): ...
    @property
    def wwzy(self): ...
    @property
    def wwzz(self): ...
    @property
    def wwzw(self): ...
    @property
    def wwwx(self): ...
    @property
    def wwwy(self): ...
    @property
    def wwwz(self): ...
    @property
    def wwww(self): ...
class float2:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
class float3:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
class float4:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def w(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def xw(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def yw(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def zw(self): ...
    @property
    def wx(self): ...
    @property
    def wy(self): ...
    @property
    def wz(self): ...
    @property
    def ww(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xxw(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xyw(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def xzw(self): ...
    @property
    def xwx(self): ...
    @property
    def xwy(self): ...
    @property
    def xwz(self): ...
    @property
    def xww(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yxw(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yyw(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def yzw(self): ...
    @property
    def ywx(self): ...
    @property
    def ywy(self): ...
    @property
    def ywz(self): ...
    @property
    def yww(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zxw(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zyw(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def zzw(self): ...
    @property
    def zwx(self): ...
    @property
    def zwy(self): ...
    @property
    def zwz(self): ...
    @property
    def zww(self): ...
    @property
    def wxx(self): ...
    @property
    def wxy(self): ...
    @property
    def wxz(self): ...
    @property
    def wxw(self): ...
    @property
    def wyx(self): ...
    @property
    def wyy(self): ...
    @property
    def wyz(self): ...
    @property
    def wyw(self): ...
    @property
    def wzx(self): ...
    @property
    def wzy(self): ...
    @property
    def wzz(self): ...
    @property
    def wzw(self): ...
    @property
    def wwx(self): ...
    @property
    def wwy(self): ...
    @property
    def wwz(self): ...
    @property
    def www(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxxw(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxyw(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xxzw(self): ...
    @property
    def xxwx(self): ...
    @property
    def xxwy(self): ...
    @property
    def xxwz(self): ...
    @property
    def xxww(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyxw(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyyw(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xyzw(self): ...
    @property
    def xywx(self): ...
    @property
    def xywy(self): ...
    @property
    def xywz(self): ...
    @property
    def xyww(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzxw(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzyw(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def xzzw(self): ...
    @property
    def xzwx(self): ...
    @property
    def xzwy(self): ...
    @property
    def xzwz(self): ...
    @property
    def xzww(self): ...
    @property
    def xwxx(self): ...
    @property
    def xwxy(self): ...
    @property
    def xwxz(self): ...
    @property
    def xwxw(self): ...
    @property
    def xwyx(self): ...
    @property
    def xwyy(self): ...
    @property
    def xwyz(self): ...
    @property
    def xwyw(self): ...
    @property
    def xwzx(self): ...
    @property
    def xwzy(self): ...
    @property
    def xwzz(self): ...
    @property
    def xwzw(self): ...
    @property
    def xwwx(self): ...
    @property
    def xwwy(self): ...
    @property
    def xwwz(self): ...
    @property
    def xwww(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxxw(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxyw(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yxzw(self): ...
    @property
    def yxwx(self): ...
    @property
    def yxwy(self): ...
    @property
    def yxwz(self): ...
    @property
    def yxww(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyxw(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyyw(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yyzw(self): ...
    @property
    def yywx(self): ...
    @property
    def yywy(self): ...
    @property
    def yywz(self): ...
    @property
    def yyww(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzxw(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzyw(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def yzzw(self): ...
    @property
    def yzwx(self): ...
    @property
    def yzwy(self): ...
    @property
    def yzwz(self): ...
    @property
    def yzww(self): ...
    @property
    def ywxx(self): ...
    @property
    def ywxy(self): ...
    @property
    def ywxz(self): ...
    @property
    def ywxw(self): ...
    @property
    def ywyx(self): ...
    @property
    def ywyy(self): ...
    @property
    def ywyz(self): ...
    @property
    def ywyw(self): ...
    @property
    def ywzx(self): ...
    @property
    def ywzy(self): ...
    @property
    def ywzz(self): ...
    @property
    def ywzw(self): ...
    @property
    def ywwx(self): ...
    @property
    def ywwy(self): ...
    @property
    def ywwz(self): ...
    @property
    def ywww(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxxw(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxyw(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zxzw(self): ...
    @property
    def zxwx(self): ...
    @property
    def zxwy(self): ...
    @property
    def zxwz(self): ...
    @property
    def zxww(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyxw(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyyw(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zyzw(self): ...
    @property
    def zywx(self): ...
    @property
    def zywy(self): ...
    @property
    def zywz(self): ...
    @property
    def zyww(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzxw(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzyw(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
    @property
    def zzzw(self): ...
    @property
    def zzwx(self): ...
    @property
    def zzwy(self): ...
    @property
    def zzwz(self): ...
    @property
    def zzww(self): ...
    @property
    def zwxx(self): ...
    @property
    def zwxy(self): ...
    @property
    def zwxz(self): ...
    @property
    def zwxw(self): ...
    @property
    def zwyx(self): ...
    @property
    def zwyy(self): ...
    @property
    def zwyz(self): ...
    @property
    def zwyw(self): ...
    @property
    def zwzx(self): ...
    @property
    def zwzy(self): ...
    @property
    def zwzz(self): ...
    @property
    def zwzw(self): ...
    @property
    def zwwx(self): ...
    @property
    def zwwy(self): ...
    @property
    def zwwz(self): ...
    @property
    def zwww(self): ...
    @property
    def wxxx(self): ...
    @property
    def wxxy(self): ...
    @property
    def wxxz(self): ...
    @property
    def wxxw(self): ...
    @property
    def wxyx(self): ...
    @property
    def wxyy(self): ...
    @property
    def wxyz(self): ...
    @property
    def wxyw(self): ...
    @property
    def wxzx(self): ...
    @property
    def wxzy(self): ...
    @property
    def wxzz(self): ...
    @property
    def wxzw(self): ...
    @property
    def wxwx(self): ...
    @property
    def wxwy(self): ...
    @property
    def wxwz(self): ...
    @property
    def wxww(self): ...
    @property
    def wyxx(self): ...
    @property
    def wyxy(self): ...
    @property
    def wyxz(self): ...
    @property
    def wyxw(self): ...
    @property
    def wyyx(self): ...
    @property
    def wyyy(self): ...
    @property
    def wyyz(self): ...
    @property
    def wyyw(self): ...
    @property
    def wyzx(self): ...
    @property
    def wyzy(self): ...
    @property
    def wyzz(self): ...
    @property
    def wyzw(self): ...
    @property
    def wywx(self): ...
    @property
    def wywy(self): ...
    @property
    def wywz(self): ...
    @property
    def wyww(self): ...
    @property
    def wzxx(self): ...
    @property
    def wzxy(self): ...
    @property
    def wzxz(self): ...
    @property
    def wzxw(self): ...
    @property
    def wzyx(self): ...
    @property
    def wzyy(self): ...
    @property
    def wzyz(self): ...
    @property
    def wzyw(self): ...
    @property
    def wzzx(self): ...
    @property
    def wzzy(self): ...
    @property
    def wzzz(self): ...
    @property
    def wzzw(self): ...
    @property
    def wzwx(self): ...
    @property
    def wzwy(self): ...
    @property
    def wzwz(self): ...
    @property
    def wzww(self): ...
    @property
    def wwxx(self): ...
    @property
    def wwxy(self): ...
    @property
    def wwxz(self): ...
    @property
    def wwxw(self): ...
    @property
    def wwyx(self): ...
    @property
    def wwyy(self): ...
    @property
    def wwyz(self): ...
    @property
    def wwyw(self): ...
    @property
    def wwzx(self): ...
    @property
    def wwzy(self): ...
    @property
    def wwzz(self): ...
    @property
    def wwzw(self): ...
    @property
    def wwwx(self): ...
    @property
    def wwwy(self): ...
    @property
    def wwwz(self): ...
    @property
    def wwww(self): ...
class bool2:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
class bool3:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
class bool4:
    def __init__(self, *args, **kwargs): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def z(self): ...
    @property
    def w(self): ...
    @property
    def xx(self): ...
    @property
    def xy(self): ...
    @property
    def xz(self): ...
    @property
    def xw(self): ...
    @property
    def yx(self): ...
    @property
    def yy(self): ...
    @property
    def yz(self): ...
    @property
    def yw(self): ...
    @property
    def zx(self): ...
    @property
    def zy(self): ...
    @property
    def zz(self): ...
    @property
    def zw(self): ...
    @property
    def wx(self): ...
    @property
    def wy(self): ...
    @property
    def wz(self): ...
    @property
    def ww(self): ...
    @property
    def xxx(self): ...
    @property
    def xxy(self): ...
    @property
    def xxz(self): ...
    @property
    def xxw(self): ...
    @property
    def xyx(self): ...
    @property
    def xyy(self): ...
    @property
    def xyz(self): ...
    @property
    def xyw(self): ...
    @property
    def xzx(self): ...
    @property
    def xzy(self): ...
    @property
    def xzz(self): ...
    @property
    def xzw(self): ...
    @property
    def xwx(self): ...
    @property
    def xwy(self): ...
    @property
    def xwz(self): ...
    @property
    def xww(self): ...
    @property
    def yxx(self): ...
    @property
    def yxy(self): ...
    @property
    def yxz(self): ...
    @property
    def yxw(self): ...
    @property
    def yyx(self): ...
    @property
    def yyy(self): ...
    @property
    def yyz(self): ...
    @property
    def yyw(self): ...
    @property
    def yzx(self): ...
    @property
    def yzy(self): ...
    @property
    def yzz(self): ...
    @property
    def yzw(self): ...
    @property
    def ywx(self): ...
    @property
    def ywy(self): ...
    @property
    def ywz(self): ...
    @property
    def yww(self): ...
    @property
    def zxx(self): ...
    @property
    def zxy(self): ...
    @property
    def zxz(self): ...
    @property
    def zxw(self): ...
    @property
    def zyx(self): ...
    @property
    def zyy(self): ...
    @property
    def zyz(self): ...
    @property
    def zyw(self): ...
    @property
    def zzx(self): ...
    @property
    def zzy(self): ...
    @property
    def zzz(self): ...
    @property
    def zzw(self): ...
    @property
    def zwx(self): ...
    @property
    def zwy(self): ...
    @property
    def zwz(self): ...
    @property
    def zww(self): ...
    @property
    def wxx(self): ...
    @property
    def wxy(self): ...
    @property
    def wxz(self): ...
    @property
    def wxw(self): ...
    @property
    def wyx(self): ...
    @property
    def wyy(self): ...
    @property
    def wyz(self): ...
    @property
    def wyw(self): ...
    @property
    def wzx(self): ...
    @property
    def wzy(self): ...
    @property
    def wzz(self): ...
    @property
    def wzw(self): ...
    @property
    def wwx(self): ...
    @property
    def wwy(self): ...
    @property
    def wwz(self): ...
    @property
    def www(self): ...
    @property
    def xxxx(self): ...
    @property
    def xxxy(self): ...
    @property
    def xxxz(self): ...
    @property
    def xxxw(self): ...
    @property
    def xxyx(self): ...
    @property
    def xxyy(self): ...
    @property
    def xxyz(self): ...
    @property
    def xxyw(self): ...
    @property
    def xxzx(self): ...
    @property
    def xxzy(self): ...
    @property
    def xxzz(self): ...
    @property
    def xxzw(self): ...
    @property
    def xxwx(self): ...
    @property
    def xxwy(self): ...
    @property
    def xxwz(self): ...
    @property
    def xxww(self): ...
    @property
    def xyxx(self): ...
    @property
    def xyxy(self): ...
    @property
    def xyxz(self): ...
    @property
    def xyxw(self): ...
    @property
    def xyyx(self): ...
    @property
    def xyyy(self): ...
    @property
    def xyyz(self): ...
    @property
    def xyyw(self): ...
    @property
    def xyzx(self): ...
    @property
    def xyzy(self): ...
    @property
    def xyzz(self): ...
    @property
    def xyzw(self): ...
    @property
    def xywx(self): ...
    @property
    def xywy(self): ...
    @property
    def xywz(self): ...
    @property
    def xyww(self): ...
    @property
    def xzxx(self): ...
    @property
    def xzxy(self): ...
    @property
    def xzxz(self): ...
    @property
    def xzxw(self): ...
    @property
    def xzyx(self): ...
    @property
    def xzyy(self): ...
    @property
    def xzyz(self): ...
    @property
    def xzyw(self): ...
    @property
    def xzzx(self): ...
    @property
    def xzzy(self): ...
    @property
    def xzzz(self): ...
    @property
    def xzzw(self): ...
    @property
    def xzwx(self): ...
    @property
    def xzwy(self): ...
    @property
    def xzwz(self): ...
    @property
    def xzww(self): ...
    @property
    def xwxx(self): ...
    @property
    def xwxy(self): ...
    @property
    def xwxz(self): ...
    @property
    def xwxw(self): ...
    @property
    def xwyx(self): ...
    @property
    def xwyy(self): ...
    @property
    def xwyz(self): ...
    @property
    def xwyw(self): ...
    @property
    def xwzx(self): ...
    @property
    def xwzy(self): ...
    @property
    def xwzz(self): ...
    @property
    def xwzw(self): ...
    @property
    def xwwx(self): ...
    @property
    def xwwy(self): ...
    @property
    def xwwz(self): ...
    @property
    def xwww(self): ...
    @property
    def yxxx(self): ...
    @property
    def yxxy(self): ...
    @property
    def yxxz(self): ...
    @property
    def yxxw(self): ...
    @property
    def yxyx(self): ...
    @property
    def yxyy(self): ...
    @property
    def yxyz(self): ...
    @property
    def yxyw(self): ...
    @property
    def yxzx(self): ...
    @property
    def yxzy(self): ...
    @property
    def yxzz(self): ...
    @property
    def yxzw(self): ...
    @property
    def yxwx(self): ...
    @property
    def yxwy(self): ...
    @property
    def yxwz(self): ...
    @property
    def yxww(self): ...
    @property
    def yyxx(self): ...
    @property
    def yyxy(self): ...
    @property
    def yyxz(self): ...
    @property
    def yyxw(self): ...
    @property
    def yyyx(self): ...
    @property
    def yyyy(self): ...
    @property
    def yyyz(self): ...
    @property
    def yyyw(self): ...
    @property
    def yyzx(self): ...
    @property
    def yyzy(self): ...
    @property
    def yyzz(self): ...
    @property
    def yyzw(self): ...
    @property
    def yywx(self): ...
    @property
    def yywy(self): ...
    @property
    def yywz(self): ...
    @property
    def yyww(self): ...
    @property
    def yzxx(self): ...
    @property
    def yzxy(self): ...
    @property
    def yzxz(self): ...
    @property
    def yzxw(self): ...
    @property
    def yzyx(self): ...
    @property
    def yzyy(self): ...
    @property
    def yzyz(self): ...
    @property
    def yzyw(self): ...
    @property
    def yzzx(self): ...
    @property
    def yzzy(self): ...
    @property
    def yzzz(self): ...
    @property
    def yzzw(self): ...
    @property
    def yzwx(self): ...
    @property
    def yzwy(self): ...
    @property
    def yzwz(self): ...
    @property
    def yzww(self): ...
    @property
    def ywxx(self): ...
    @property
    def ywxy(self): ...
    @property
    def ywxz(self): ...
    @property
    def ywxw(self): ...
    @property
    def ywyx(self): ...
    @property
    def ywyy(self): ...
    @property
    def ywyz(self): ...
    @property
    def ywyw(self): ...
    @property
    def ywzx(self): ...
    @property
    def ywzy(self): ...
    @property
    def ywzz(self): ...
    @property
    def ywzw(self): ...
    @property
    def ywwx(self): ...
    @property
    def ywwy(self): ...
    @property
    def ywwz(self): ...
    @property
    def ywww(self): ...
    @property
    def zxxx(self): ...
    @property
    def zxxy(self): ...
    @property
    def zxxz(self): ...
    @property
    def zxxw(self): ...
    @property
    def zxyx(self): ...
    @property
    def zxyy(self): ...
    @property
    def zxyz(self): ...
    @property
    def zxyw(self): ...
    @property
    def zxzx(self): ...
    @property
    def zxzy(self): ...
    @property
    def zxzz(self): ...
    @property
    def zxzw(self): ...
    @property
    def zxwx(self): ...
    @property
    def zxwy(self): ...
    @property
    def zxwz(self): ...
    @property
    def zxww(self): ...
    @property
    def zyxx(self): ...
    @property
    def zyxy(self): ...
    @property
    def zyxz(self): ...
    @property
    def zyxw(self): ...
    @property
    def zyyx(self): ...
    @property
    def zyyy(self): ...
    @property
    def zyyz(self): ...
    @property
    def zyyw(self): ...
    @property
    def zyzx(self): ...
    @property
    def zyzy(self): ...
    @property
    def zyzz(self): ...
    @property
    def zyzw(self): ...
    @property
    def zywx(self): ...
    @property
    def zywy(self): ...
    @property
    def zywz(self): ...
    @property
    def zyww(self): ...
    @property
    def zzxx(self): ...
    @property
    def zzxy(self): ...
    @property
    def zzxz(self): ...
    @property
    def zzxw(self): ...
    @property
    def zzyx(self): ...
    @property
    def zzyy(self): ...
    @property
    def zzyz(self): ...
    @property
    def zzyw(self): ...
    @property
    def zzzx(self): ...
    @property
    def zzzy(self): ...
    @property
    def zzzz(self): ...
    @property
    def zzzw(self): ...
    @property
    def zzwx(self): ...
    @property
    def zzwy(self): ...
    @property
    def zzwz(self): ...
    @property
    def zzww(self): ...
    @property
    def zwxx(self): ...
    @property
    def zwxy(self): ...
    @property
    def zwxz(self): ...
    @property
    def zwxw(self): ...
    @property
    def zwyx(self): ...
    @property
    def zwyy(self): ...
    @property
    def zwyz(self): ...
    @property
    def zwyw(self): ...
    @property
    def zwzx(self): ...
    @property
    def zwzy(self): ...
    @property
    def zwzz(self): ...
    @property
    def zwzw(self): ...
    @property
    def zwwx(self): ...
    @property
    def zwwy(self): ...
    @property
    def zwwz(self): ...
    @property
    def zwww(self): ...
    @property
    def wxxx(self): ...
    @property
    def wxxy(self): ...
    @property
    def wxxz(self): ...
    @property
    def wxxw(self): ...
    @property
    def wxyx(self): ...
    @property
    def wxyy(self): ...
    @property
    def wxyz(self): ...
    @property
    def wxyw(self): ...
    @property
    def wxzx(self): ...
    @property
    def wxzy(self): ...
    @property
    def wxzz(self): ...
    @property
    def wxzw(self): ...
    @property
    def wxwx(self): ...
    @property
    def wxwy(self): ...
    @property
    def wxwz(self): ...
    @property
    def wxww(self): ...
    @property
    def wyxx(self): ...
    @property
    def wyxy(self): ...
    @property
    def wyxz(self): ...
    @property
    def wyxw(self): ...
    @property
    def wyyx(self): ...
    @property
    def wyyy(self): ...
    @property
    def wyyz(self): ...
    @property
    def wyyw(self): ...
    @property
    def wyzx(self): ...
    @property
    def wyzy(self): ...
    @property
    def wyzz(self): ...
    @property
    def wyzw(self): ...
    @property
    def wywx(self): ...
    @property
    def wywy(self): ...
    @property
    def wywz(self): ...
    @property
    def wyww(self): ...
    @property
    def wzxx(self): ...
    @property
    def wzxy(self): ...
    @property
    def wzxz(self): ...
    @property
    def wzxw(self): ...
    @property
    def wzyx(self): ...
    @property
    def wzyy(self): ...
    @property
    def wzyz(self): ...
    @property
    def wzyw(self): ...
    @property
    def wzzx(self): ...
    @property
    def wzzy(self): ...
    @property
    def wzzz(self): ...
    @property
    def wzzw(self): ...
    @property
    def wzwx(self): ...
    @property
    def wzwy(self): ...
    @property
    def wzwz(self): ...
    @property
    def wzww(self): ...
    @property
    def wwxx(self): ...
    @property
    def wwxy(self): ...
    @property
    def wwxz(self): ...
    @property
    def wwxw(self): ...
    @property
    def wwyx(self): ...
    @property
    def wwyy(self): ...
    @property
    def wwyz(self): ...
    @property
    def wwyw(self): ...
    @property
    def wwzx(self): ...
    @property
    def wwzy(self): ...
    @property
    def wwzz(self): ...
    @property
    def wwzw(self): ...
    @property
    def wwwx(self): ...
    @property
    def wwwy(self): ...
    @property
    def wwwz(self): ...
    @property
    def wwww(self): ...
class FsPath:
    def __init__(self, *args, **kwargs): ...
class Context:
    def __init__(self, *args, **kwargs): ...
class Device:
    def __init__(self, *args, **kwargs): ...
class DeviceInterface:
    def __init__(self, *args, **kwargs): ...
class Stream:
    def __init__(self, *args, **kwargs): ...
class Function:
    def __init__(self, *args, **kwargs): ...
class FunctionBuilder:
    def __init__(self, *args, **kwargs): ...
class Expression:
    def __init__(self, *args, **kwargs): ...
class LiteralExpr:
    def __init__(self, *args, **kwargs): ...
class RefExpr:
    def __init__(self, *args, **kwargs): ...
class CallExpr:
    def __init__(self, *args, **kwargs): ...
class UnaryExpr:
    def __init__(self, *args, **kwargs): ...
class BinaryExpr:
    def __init__(self, *args, **kwargs): ...
class MemberExpr:
    def __init__(self, *args, **kwargs): ...
class AccessExpr:
    def __init__(self, *args, **kwargs): ...
class CastExpr:
    def __init__(self, *args, **kwargs): ...
class ScopeStmt:
    def __init__(self, *args, **kwargs): ...
class IfStmt:
    def __init__(self, *args, **kwargs): ...
class LoopStmt:
    def __init__(self, *args, **kwargs): ...
class ForStmt:
    def __init__(self, *args, **kwargs): ...
class Type:
    def __init__(self, *args, **kwargs): ...
class Command:
    def __init__(self, *args, **kwargs): ...
class ShaderDispatchCommand:
    def __init__(self, *args, **kwargs): ...
class BufferUploadCommand:
    def __init__(self, *args, **kwargs): ...
class BufferDownloadCommand:
    def __init__(self, *args, **kwargs): ...
class BufferCopyCommand:
    def __init__(self, *args, **kwargs): ...
class TextureUploadCommand:
    def __init__(self, *args, **kwargs): ...
class TextureDownloadCommand:
    def __init__(self, *args, **kwargs): ...
class TextureCopyCommand:
    def __init__(self, *args, **kwargs): ...
class BufferToTextureCopyCommand:
    def __init__(self, *args, **kwargs): ...
class TextureToBufferCopyCommand:
    def __init__(self, *args, **kwargs): ...
class MeshBuildCommand:
    def __init__(self, *args, **kwargs): ...
class AccelBuildCommand:
    def __init__(self, *args, **kwargs): ...
class BindlessArrayUpdateCommand:
    def __init__(self, *args, **kwargs): ...
class Accel:
    def __init__(self, *args, **kwargs): ...
class AccelModification:
    def __init__(self, *args, **kwargs): ...
class Sampler:
    def __init__(self, *args, **kwargs): ...
