// Host-only unit tests for the CUDA PTX `.version` patcher.
//
// The patcher is a pure string/byte edit (see cuda_ptx_version.h) so these
// tests need neither a CUDA driver/GPU nor the rest of the CUDA backend; they
// include the header directly and validate the exact text transformation plus
// the byte-vector NUL-termination contract used by cuModuleLoadData.

#include "ut/ut.hpp"

#include <cstddef>
#include <string>
#include <string_view>

#include "../backends/cuda/cuda_ptx_version.h"

using namespace luisa;
using namespace luisa::compute::cuda;
using namespace boost::ut;

namespace {

void expect_patched(luisa::string input, luisa::string expected) {
    patch_cuda_ptx_version(input);
    expect(input == expected) << input;
}

void test_basic_version_downgrade() {
    expect_patched(".version 8.3\n.target sm_86\n", ".version 8.0\n.target sm_86\n");
    expect_patched(".version 7.5\n", ".version 7.0\n");
}

void test_rest_of_buffer_unchanged() {
    auto input = luisa::string{
        "// generated by luisa\n"
        ".version 8.4\n"
        ".target sm_80\n"
        ".address_size 64\n"
        "\n"
        ".visible .entry kernel_main(.param .b64 kernel_main_param_0) {\n"
        "    ret;\n"
        "}\n"};
    auto expected = input;
    auto version = expected.find(".version ");
    version += luisa::string_view{".version "}.size();
    expected.replace(version, 3u, "8.0");
    expect_patched(std::move(input), expected);
}

void test_leading_comments_and_whitespace() {
    expect_patched("// header comment\n\n    .version 8.1\n", "// header comment\n\n    .version 8.0\n");
    expect_patched("\t .version 8.9\n", "\t .version 8.0\n");
}

void test_missing_version_is_unchanged() {
    auto input = luisa::string{".target sm_80\nret;\n"};
    auto before = input;
    patch_cuda_ptx_version(input);
    expect(input == before) << input;
}

void test_malformed_or_empty_version_is_unchanged() {
    auto cases = {
        luisa::string{".version\n"},
        luisa::string{".version \n"},
        luisa::string{".version 8\n"},
        luisa::string{".version 8.\n"},
        luisa::string{".version .\n"},
        luisa::string{"version 8.3\n"},// no leading dot
    };
    for (auto input : cases) {
        auto before = input;
        patch_cuda_ptx_version(input);
        expect(input == before) << input;
    }
}

void test_multi_digit_minor_is_normalized() {
    expect_patched(".version 8.13\n", ".version 8.0\n");
    expect_patched(".version 8.3.2\n", ".version 8.0\n");
}

void test_byte_vector_wrapper_keeps_single_trailing_nul() {
    auto make_bytes = [](luisa::string_view text, bool terminate) {
        luisa::vector<std::byte> bytes;
        bytes.reserve(text.size() + 1u);
        for (char c : text) {
            bytes.emplace_back(static_cast<std::byte>(static_cast<unsigned char>(c)));
        }
        if (terminate) { bytes.push_back(std::byte{0}); }
        return bytes;
    };
    for (auto terminate : {false, true}) {
        auto bytes = make_bytes(".version 8.3\n.target sm_86\n", terminate);
        patch_cuda_ptx_version_bytes(bytes);
        expect(!bytes.empty());
        expect(bytes.back() == std::byte{0});
        luisa::string_view patched{
            reinterpret_cast<const char *>(bytes.data()),
            bytes.size() - 1u};
        expect(patched == luisa::string_view{".version 8.0\n.target sm_86\n"}) << patched;
    }
}

void test_byte_vector_wrapper_missing_version_keeps_nul() {
    luisa::vector<std::byte> bytes;
    auto text = luisa::string_view{"ret;\n"};
    bytes.reserve(text.size() + 1u);
    for (char c : text) {
        bytes.emplace_back(static_cast<std::byte>(static_cast<unsigned char>(c)));
    }
    bytes.push_back(std::byte{0});
    patch_cuda_ptx_version_bytes(bytes);
    expect(bytes.back() == std::byte{0});
    luisa::string_view content{
        reinterpret_cast<const char *>(bytes.data()),
        bytes.size() - 1u};
    expect(content == text) << content;
}

}// namespace

int main(int argc, char *argv[]) {
    boost::ut::detail::cfg::parse_arg_with_fallback(argc, const_cast<const char **>(argv));
    "cuda_ptx_version_basic_downgrade"_test = test_basic_version_downgrade;
    "cuda_ptx_version_rest_unchanged"_test = test_rest_of_buffer_unchanged;
    "cuda_ptx_version_leading_comments_whitespace"_test = test_leading_comments_and_whitespace;
    "cuda_ptx_version_missing_unchanged"_test = test_missing_version_is_unchanged;
    "cuda_ptx_version_malformed_unchanged"_test = test_malformed_or_empty_version_is_unchanged;
    "cuda_ptx_version_multi_digit_minor"_test = test_multi_digit_minor_is_normalized;
    "cuda_ptx_version_byte_wrapper_nul"_test = test_byte_vector_wrapper_keeps_single_trailing_nul;
    "cuda_ptx_version_byte_wrapper_missing_nul"_test = test_byte_vector_wrapper_missing_version_keeps_nul;
}
