// !!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!
// !!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!

#pragma once

extern "C" const unsigned long long luisa_compute_metal_builtin_kernels_size;
extern "C" const char luisa_compute_metal_builtin_kernels[];

extern "C" const unsigned long long luisa_compute_metal_device_lib_size;
extern "C" const char luisa_compute_metal_device_lib[];
