// !!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!
// !!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!

#pragma once

extern "C" const unsigned long long luisa_compute_cuda_libdevice_10_size;
extern "C" const unsigned char luisa_compute_cuda_libdevice_10[];
