#pragma once
#define position clang::annotate("luisa-shader", "position")
#define normal clang::annotate("luisa-shader", "normal")
#define tangent clang::annotate("luisa-shader", "tangent")
#define uv0 clang::annotate("luisa-shader", "uv0")
#define uv1 clang::annotate("luisa-shader", "uv1")
#define uv2 clang::annotate("luisa-shader", "uv2")
#define uv3 clang::annotate("luisa-shader", "uv3")
#define vertex_id clang::annotate("luisa-shader", "vertex_id")
#define instance_id clang::annotate("luisa-shader", "instance_id")
#define is_front_face clang::annotate("luisa-shader", "is_front_face")
#define vertex_shader clang::annotate("luisa-shader", "vertex")
#define pixel_shader clang::annotate("luisa-shader", "pixel")
