#pragma once
#define POSITION clang::annotate("luisa", "position")
#define NORMAL clang::annotate("luisa", "normal")
#define TANGENT clang::annotate("luisa", "tangent")
#define UV0 clang::annotate("luisa", "uv0")
#define UV1 clang::annotate("luisa", "uv1")
#define UV2 clang::annotate("luisa", "uv2")
#define UV3 clang::annotate("luisa", "uv3")
#define VERTEX_ID clang::annotate("luisa", "vertex_id")
#define INSTANCE_ID clang::annotate("luisa", "instance_id")
#define IS_FRONTFACE clang::annotate("luisa", "is_front_face")
#define VERTEX_SHADER clang::annotate("luisa", "vertex")
#define PIXEL_SHADER clang::annotate("luisa", "pixel")
