// !!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!
// !!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!

#pragma once

extern "C" const unsigned long long luisa_compute_cuda_builtin_kernels_size;
extern "C" const unsigned char luisa_compute_cuda_builtin_kernels[];

extern "C" const unsigned long long luisa_compute_cuda_device_coop_size;
extern "C" const unsigned char luisa_compute_cuda_device_coop[];

extern "C" const unsigned long long luisa_compute_cuda_device_half_size;
extern "C" const unsigned char luisa_compute_cuda_device_half[];

extern "C" const unsigned long long luisa_compute_cuda_device_math_size;
extern "C" const unsigned char luisa_compute_cuda_device_math[];

extern "C" const unsigned long long luisa_compute_cuda_device_resource_size;
extern "C" const unsigned char luisa_compute_cuda_device_resource[];
