// Unit tests for the CUDA native-shader reflection
// (src/backends/cuda/native_shader_reflection.h).
//
// These tests need no device and no CUDA toolkit: the reflection is a pure
// function of (PTX text, CUDA source), and the PTX fixture below is the *real*
// output of the backend's NVRTC helper (luisa_nvrtc / cuda_nvrtc_compiler.cpp)
// for the corresponding source, so the two halves of the reflection are
// exercised exactly as they are at runtime.
//
// Covered behaviour:
//  * PTX: entry-point selection, per-parameter size/alignment, `.maxntid`, and
//    the fail-closed paths (no entry, unknown entry, malformed module),
//  * source: `__global__` discovery through comments/literals, attributes
//    (`extern "C"`, `__launch_bounds__`), and the buffer/scalar classification
//    (`const T *` => read-only, `T *` => writable, everything else => scalar),
//  * merge: buffer-vs-scalar mapping, canonical buffer order, and the
//    fail-closed cross-checks (parameter count, 64-bit pointers).
#include "ut/ut.hpp"

#include <luisa/core/stl/string.h>
#include <luisa/core/stl/vector.h>

#include "native_shader_reflection.h"

using namespace luisa;
using namespace luisa::compute::cuda::native_shader;
using namespace boost::ut;
using namespace boost::ut::literals;

namespace {

// Real NVRTC output (PTX ISA 8.8, sm_89) for:
//
//   struct Factors { float scale; float bias; unsigned int n; };
//   extern "C" __global__ void scale(float *dst, const float *src, float k, unsigned int n);
//   extern "C" __global__ void __launch_bounds__(256) scaled_struct(float *p, Factors f);
//
// (Bodies trimmed: only the entry headers, the parameter lists and `.maxntid`
// matter to the reflection, and the fixture keeps them verbatim.)
constexpr auto real_ptx = R"(//
// Generated by NVIDIA NVVM Compiler
//
.version 8.8
.target sm_89
.address_size 64

	// .globl	scale
.visible .entry scale(
	.param .u64 scale_param_0,
	.param .u64 scale_param_1,
	.param .f32 scale_param_2,
	.param .u32 scale_param_3
)
{
	.reg .b32 	%r<6>;
	ret;
}

	// .globl	scaled_struct
.visible .entry scaled_struct(
	.param .u64 scaled_struct_param_0,
	.param .align 4 .b8 scaled_struct_param_1[12]
)
.maxntid 256, 1, 1
{
	.reg .b32 	%r<6>;
	ret;
}

	// .globl	_Z14mangled_kernelPf
.visible .entry _Z14mangled_kernelPf(
	.param .u64 _Z14mangled_kernelPf_param_0
)
{
	ret;
}
)";

constexpr auto real_source = R"(
struct Factors { float scale; float bias; unsigned int n; };

extern "C" __global__ void scale(float *dst, const float *src, float k, unsigned int n) {
    auto i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n) { dst[i] = src[i] * k; }
}

extern "C" __global__ void __launch_bounds__(256) scaled_struct(float *p, Factors f) {
    auto i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < f.n) { p[i] = p[i] * f.scale + f.bias; }
}
)";

}// namespace

int main() {

    "cuda_reflection_ptx_parameter_layout"_test = [] {
        auto module = reflect_ptx(real_ptx, "scale");
        expect(module.ok()) << module.error;
        expect(module.entry_point == "scale");
        expect(all(module.block_size == make_uint3(0u))) << "scale declares no __launch_bounds__";
        expect(module.parameters.size() == 4u);
        expect(module.parameters[0].size == 8u);
        expect(module.parameters[0].alignment == 8u);
        expect(module.parameters[1].size == 8u);
        expect(module.parameters[2].size == 4u);
        expect(module.parameters[2].alignment == 4u);
        expect(module.parameters[3].size == 4u);
    };

    "cuda_reflection_ptx_block_size_and_aggregate_parameter"_test = [] {
        auto module = reflect_ptx(real_ptx, "scaled_struct");
        expect(module.ok()) << module.error;
        expect(all(module.block_size == make_uint3(256u, 1u, 1u)));
        expect(module.parameters.size() == 2u);
        expect(module.parameters[0].size == 8u);
        // `Factors` is passed by value: the compiled layout is a 12-byte blob.
        expect(module.parameters[1].size == 12u);
        expect(module.parameters[1].alignment == 4u);
    };

    "cuda_reflection_ptx_entry_selection"_test = [] {
        // no explicit entry: the module declares three, so this fails closed
        auto all = reflect_ptx(real_ptx, "");
        expect(!all.ok());
        expect(all.error.find("scale") != luisa::string::npos);
        expect(all.entry_names.size() == 3u);
        expect(all.entry_names[0] == "scale");
        expect(all.entry_names[1] == "scaled_struct");
        // an unknown entry names the mangling trap explicitly
        auto missing = reflect_ptx(real_ptx, "mangled_kernel");
        expect(!missing.ok());
        expect(missing.error.find("extern \"C\"") != luisa::string::npos);
        // a single-entry module needs no explicit entry
        constexpr auto single_entry_ptx = R"(
.version 8.8
.target sm_89
.address_size 64

.visible .entry only(
	.param .u64 only_param_0,
	.param .align 4 .b8 only_param_1[8]
)
{
	ret;
}
)";
        auto single = reflect_ptx(single_entry_ptx, "");
        expect(single.ok()) << single.error;
        expect(single.entry_point == "only");
        expect(single.parameters.size() == 2u);
        expect(single.parameters[1].size == 8u);
    };

    "cuda_reflection_ptx_malformed_modules_are_rejected"_test = [] {
        expect(!reflect_ptx("", "k").ok());
        expect(!reflect_ptx(".version 8.8\n.target sm_89\n", "k").ok())
            << "a module without a kernel must be rejected";
        expect(!reflect_ptx(".visible .entry k(\n", "k").ok())
            << "an unterminated parameter list must be rejected";
        auto unknown_type = reflect_ptx(
            ".visible .entry k(\n\t.param .b128 k_param_0\n)\n{\n\tret;\n}\n", "k");
        expect(!unknown_type.ok());
        expect(unknown_type.error.find("unsupported type") != luisa::string::npos);
    };

    "cuda_reflection_source_signature_is_classified"_test = [] {
        auto source = reflect_source(real_source, "scale");
        expect(source.ok()) << source.error;
        expect(source.entry_point == "scale");
        expect(source.kernel_names.size() == 2u);
        expect(source.parameters.size() == 4u);
        expect(source.parameters[0].is_buffer && !source.parameters[0].read_only)
            << "`float *dst` is a writable buffer";
        expect(source.parameters[1].is_buffer && source.parameters[1].read_only)
            << "`const float *src` is a read-only buffer";
        expect(!source.parameters[2].is_buffer) << "`float k` is a scalar";
        expect(!source.parameters[3].is_buffer) << "`unsigned int n` is a scalar";
        // the default entry selects the only kernel, and fails with several
        auto ambiguous = reflect_source(real_source, "");
        expect(!ambiguous.ok());
        expect(ambiguous.error.find("scale") != luisa::string::npos);
        expect(ambiguous.error.find("scaled_struct") != luisa::string::npos);
        // ... and an unknown one is reported with the declared names
        auto unknown = reflect_source(real_source, "nope");
        expect(!unknown.ok());
        expect(unknown.error.find("nope") != luisa::string::npos);
    };

    "cuda_reflection_source_handles_attributes_and_comments"_test = [] {
        constexpr auto source_with_noise = R"CUDA(
// a comment mentioning __global__ void fake(float *a, float *b) {}
/* a block comment mentioning __global__ void fake2(const float *a) {} */
constexpr auto text = "__global__ void fake3(float *a)";
extern "C" __global__ void __launch_bounds__(128) __maxnreg__(32) kernel(
    const float *__restrict__ a,
    float *__restrict__ b,
    unsigned int n) {
    (void)__global__;
}
)CUDA";
        auto source = reflect_source(source_with_noise, "kernel");
        expect(source.ok()) << source.error;
        expect(source.parameters.size() == 3u);
        expect(source.parameters[0].is_buffer && source.parameters[0].read_only);
        expect(source.parameters[1].is_buffer && !source.parameters[1].read_only);
        expect(!source.parameters[2].is_buffer);
    };

    "cuda_reflection_source_rejects_unsupported_parameters"_test = [] {
        auto array = reflect_source(
            "extern \"C\" __global__ void k(float a[4]) {}", "k");
        expect(!array.ok());
        expect(array.error.find("array") != luisa::string::npos);
        auto reference = reflect_source(
            "extern \"C\" __global__ void k(float &a) {}", "k");
        expect(!reference.ok());
        auto variadic = reflect_source(
            "extern \"C\" __global__ void k(float *a, ...) {}", "k");
        expect(!variadic.ok());
        auto no_kernel = reflect_source("int main() { return 0; }", "k");
        expect(!no_kernel.ok());
        expect(no_kernel.error.find("__global__") != luisa::string::npos);
    };

    "cuda_reflection_merge_maps_buffers_and_scalars"_test = [] {
        auto module = reflect_ptx(real_ptx, "scale");
        auto source = reflect_source(real_source, "scale");
        expect(module.ok() && source.ok());
        auto merged = merge(std::move(module), source);
        expect(merged.ok()) << merged.error;
        expect(merged.entry_point == "scale");
        expect(merged.parameters.size() == 4u);
        expect(merged.buffer_count() == 2u);
        expect(merged.scalar_count() == 2u);
        expect(merged.uniform_bytes == 8u) << "float + unsigned int";
        expect(merged.buffer_parameter_index(0u) == 0u);
        expect(merged.buffer_parameter_index(1u) == 1u);
        expect(merged.parameters[1].read_only);
        expect(!merged.parameters[0].read_only);
        // the aggregate parameter of the other kernel keeps the scalar mapping
        auto struct_module = reflect_ptx(real_ptx, "scaled_struct");
        auto struct_source = reflect_source(real_source, "scaled_struct");
        auto struct_merged = merge(std::move(struct_module), struct_source);
        expect(struct_merged.ok()) << struct_merged.error;
        expect(struct_merged.parameters.size() == 2u);
        expect(struct_merged.parameters[1].size == 12u);
        expect(!struct_merged.parameters[1].is_buffer)
            << "a by-value struct is a uniform parameter, not a binding";
        expect(struct_merged.uniform_bytes == 12u);
        expect(all(struct_merged.block_size == make_uint3(256u, 1u, 1u)));
    };

    "cuda_reflection_merge_is_fail_closed"_test = [] {
        // the PTX has 4 parameters, the source 2: the reflection must refuse
        auto module = reflect_ptx(real_ptx, "scale");
        auto truncated = reflect_source(
            "extern \"C\" __global__ void scale(float *dst, const float *src) {}", "scale");
        auto mismatch = merge(std::move(module), truncated);
        expect(!mismatch.ok());
        expect(mismatch.error.find("parameter") != luisa::string::npos);
        // a "pointer" parameter that is not 64 bits wide cannot be addressed
        auto narrow_ptx = reflect_ptx(
            ".visible .entry k(\n\t.param .u32 k_param_0\n)\n{\n\tret;\n}\n", "k");
        auto narrow_source = reflect_source(
            "extern \"C\" __global__ void k(float *a) {}", "k");
        auto narrow = merge(std::move(narrow_ptx), narrow_source);
        expect(!narrow.ok());
        expect(narrow.error.find("64-bit") != luisa::string::npos);
        // ... and a scalar parameter must have a size
        auto huge_ptx = reflect_ptx(
            ".visible .entry k(\n\t.param .u64 k_param_0,\n"
            "\t.param .align 4 .b8 k_param_1[8]\n)\n{\n\tret;\n}\n", "k");
        auto huge_source = reflect_source(
            "extern \"C\" __global__ void k(float *a, double b) {}", "k");
        auto huge = merge(std::move(huge_ptx), huge_source);
        expect(huge.ok()) << huge.error;
        expect(huge.uniform_bytes == 8u);
    };

    return 0;
}
