// This file is generated by update_op_name_map.py
// Do not edit it manually.

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(AllocaOp op) noexcept;
[[nodiscard]] LUISA_XIR_API AllocaOp alloca_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(ArithmeticOp op) noexcept;
[[nodiscard]] LUISA_XIR_API ArithmeticOp arithmetic_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(AtomicOp op) noexcept;
[[nodiscard]] LUISA_XIR_API AtomicOp atomic_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(AutodiffIntrinsicOp op) noexcept;
[[nodiscard]] LUISA_XIR_API AutodiffIntrinsicOp autodiff_intrinsic_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(CastOp op) noexcept;
[[nodiscard]] LUISA_XIR_API CastOp cast_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(RayQueryObjectReadOp op) noexcept;
[[nodiscard]] LUISA_XIR_API RayQueryObjectReadOp ray_query_object_read_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(RayQueryObjectWriteOp op) noexcept;
[[nodiscard]] LUISA_XIR_API RayQueryObjectWriteOp ray_query_object_write_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(ResourceQueryOp op) noexcept;
[[nodiscard]] LUISA_XIR_API ResourceQueryOp resource_query_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(ResourceReadOp op) noexcept;
[[nodiscard]] LUISA_XIR_API ResourceReadOp resource_read_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(ResourceWriteOp op) noexcept;
[[nodiscard]] LUISA_XIR_API ResourceWriteOp resource_write_op_from_string(luisa::string_view name) noexcept;

[[nodiscard]] LUISA_XIR_API luisa::string_view to_string(ThreadGroupOp op) noexcept;
[[nodiscard]] LUISA_XIR_API ThreadGroupOp thread_group_op_from_string(luisa::string_view name) noexcept;

