
#pragma once
#include <VEngineConfig.h>
#include <DirectXMath.h>
#include <DirectXPackedVector.h>
#include <DirectXColors.h>
#include <memory>
//#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <cassert>
#include <Common/DLL.h>
#include <Common/MCollection.h>
#include <Common/Log.h>
#include <Common/DXMath/DXMath.h>
#include <Common/MathHelper.h>
