#pragma once

#include <luisa/ast/ast2json.h>
#include <luisa/ast/atomic_ref_node.h>
#include <luisa/ast/attribute.h>
#include <luisa/ast/callable_library.h>
#include <luisa/ast/constant_data.h>
#include <luisa/ast/expression.h>
#include <luisa/ast/external_function.h>
#include <luisa/ast/function.h>
#include <luisa/ast/function_builder.h>
#include <luisa/ast/interface.h>
#include <luisa/ast/op.h>
#include <luisa/ast/statement.h>
#include <luisa/ast/type.h>
#include <luisa/ast/type_registry.h>
#include <luisa/ast/usage.h>
#include <luisa/ast/variable.h>

#ifdef LUISA_ENABLE_CLANGCXX
#include <luisa/clangcxx/ast.h>
#include <luisa/clangcxx/compiler.h>
#endif

#include <luisa/core/basic_traits.h>
#include <luisa/core/basic_types.h>
#include <luisa/core/binary_buffer.h>
#include <luisa/core/binary_file_stream.h>
#include <luisa/core/binary_io.h>
#include <luisa/core/clock.h>
#include <luisa/core/concepts.h>
#include <luisa/core/constants.h>
#include <luisa/core/dll_export.h>
#include <luisa/core/dynamic_module.h>
#include <luisa/core/fiber.h>
#include <luisa/core/first_fit.h>
#include <luisa/core/forget.h>
#include <luisa/core/intrin.h>
#include <luisa/core/logging.h>
#include <luisa/core/macro.h>
#include <luisa/core/magic_enum.h>
#include <luisa/core/mathematics.h>
#include <luisa/core/platform.h>
#include <luisa/core/pool.h>
#include <luisa/core/shared_function.h>
#include <luisa/core/spin_mutex.h>
#include <luisa/core/stl.h>
#include <luisa/core/string_scratch.h>
#include <luisa/core/thread_safety.h>

#ifdef LUISA_ENABLE_DSL
#include <luisa/dsl/arg.h>
#include <luisa/dsl/atomic.h>
#include <luisa/dsl/binding_group.h>
#include <luisa/dsl/builtin.h>
#include <luisa/dsl/callable_library.h>
#include <luisa/dsl/constant.h>
#include <luisa/dsl/dispatch_indirect.h>
#include <luisa/dsl/expr.h>
#include <luisa/dsl/expr_traits.h>
#include <luisa/dsl/func.h>
#include <luisa/dsl/local.h>
#include <luisa/dsl/operators.h>
#include <luisa/dsl/polymorphic.h>
#include <luisa/dsl/raster/raster_func.h>
#include <luisa/dsl/raster/raster_kernel.h>
#include <luisa/dsl/ref.h>
#include <luisa/dsl/resource.h>
#include <luisa/dsl/rtx/aabb.h>
#include <luisa/dsl/rtx/accel.h>
#include <luisa/dsl/rtx/curve.h>
#include <luisa/dsl/rtx/hit.h>
#include <luisa/dsl/rtx/ray.h>
#include <luisa/dsl/rtx/ray_query.h>
#include <luisa/dsl/rtx/triangle.h>
#include <luisa/dsl/shared.h>
#include <luisa/dsl/soa.h>
#include <luisa/dsl/stmt.h>
#include <luisa/dsl/struct.h>
#include <luisa/dsl/sugar.h>
#include <luisa/dsl/syntax.h>
#include <luisa/dsl/var.h>
#endif

#ifdef LUISA_ENABLE_GUI
#include <luisa/gui/framerate.h>
#include <luisa/gui/imgui_window.h>
#include <luisa/gui/input.h>
#include <luisa/gui/window.h>
#endif

#ifdef LUISA_ENABLE_IR
#include <luisa/ir/ast2ir.h>
#include <luisa/ir/fwd.h>
#include <luisa/ir/ir2ast.h>
#include <luisa/ir/transform.h>
#endif

#include <luisa/osl/hint.h>
#include <luisa/osl/instruction.h>
#include <luisa/osl/literal.h>
#include <luisa/osl/oso_parser.h>
#include <luisa/osl/shader.h>
#include <luisa/osl/symbol.h>
#include <luisa/osl/type.h>

#include <luisa/runtime/bindless_array.h>
#include <luisa/runtime/buffer.h>
#include <luisa/runtime/buffer_arena.h>
#include <luisa/runtime/byte_buffer.h>
#include <luisa/runtime/command_list.h>
#include <luisa/runtime/context.h>
#include <luisa/runtime/depth_format.h>
#include <luisa/runtime/device.h>
#include <luisa/runtime/dispatch_buffer.h>
#include <luisa/runtime/event.h>
#include <luisa/runtime/image.h>
#include <luisa/runtime/mipmap.h>
#include <luisa/runtime/raster/app_data.h>
#include <luisa/runtime/raster/depth_buffer.h>
#include <luisa/runtime/raster/raster_scene.h>
#include <luisa/runtime/raster/raster_shader.h>
#include <luisa/runtime/raster/raster_state.h>
#include <luisa/runtime/raster/vertex_attribute.h>
#include <luisa/runtime/raster/viewport.h>
#include <luisa/runtime/remote/client_interface.h>
#include <luisa/runtime/remote/server_interface.h>
#include <luisa/runtime/rhi/argument.h>
#include <luisa/runtime/rhi/command.h>
#include <luisa/runtime/rhi/command_encoder.h>
#include <luisa/runtime/rhi/curve_basis.h>
#include <luisa/runtime/rhi/device_interface.h>
#include <luisa/runtime/rhi/pixel.h>
#include <luisa/runtime/rhi/resource.h>
#include <luisa/runtime/rhi/sampler.h>
#include <luisa/runtime/rhi/stream_tag.h>
#include <luisa/runtime/rhi/tile_modification.h>
#include <luisa/runtime/rtx/aabb.h>
#include <luisa/runtime/rtx/accel.h>
#include <luisa/runtime/rtx/curve.h>
#include <luisa/runtime/rtx/hit.h>
#include <luisa/runtime/rtx/mesh.h>
#include <luisa/runtime/rtx/motion_instance.h>
#include <luisa/runtime/rtx/motion_transform.h>
#include <luisa/runtime/rtx/procedural_primitive.h>
#include <luisa/runtime/rtx/ray.h>
#include <luisa/runtime/rtx/triangle.h>
#include <luisa/runtime/shader.h>
#include <luisa/runtime/sparse_buffer.h>
#include <luisa/runtime/sparse_command_list.h>
#include <luisa/runtime/sparse_heap.h>
#include <luisa/runtime/sparse_image.h>
#include <luisa/runtime/sparse_texture.h>
#include <luisa/runtime/sparse_volume.h>
#include <luisa/runtime/stream.h>
#include <luisa/runtime/stream_event.h>
#include <luisa/runtime/swapchain.h>
#include <luisa/runtime/volume.h>

#ifdef LUISA_ENABLE_RUST
#include <luisa/rust/api_types.h>
#include <luisa/rust/api_types.hpp>
#include <luisa/rust/ir.hpp>
#include <luisa/rust/ir_common.h>
#endif

#ifdef LUISA_ENABLE_TENSOR
#include <luisa/tensor/scope.h>
#include <luisa/tensor/tensor.h>
#endif

#include <luisa/vstl/allocate_type.h>
#include <luisa/vstl/arena_hash_map.h>
#include <luisa/vstl/common.h>
#include <luisa/vstl/compare.h>
#include <luisa/vstl/config.h>
#include <luisa/vstl/functional.h>
#include <luisa/vstl/hash.h>
#include <luisa/vstl/hash_map.h>
#include <luisa/vstl/lmdb.hpp>
#include <luisa/vstl/lockfree_array_queue.h>
#include <luisa/vstl/log.h>
#include <luisa/vstl/md5.h>
#include <luisa/vstl/memory.h>
#include <luisa/vstl/meta_lib.h>
#include <luisa/vstl/pool.h>
#include <luisa/vstl/ranges.h>
#include <luisa/vstl/spin_mutex.h>
#include <luisa/vstl/stack_allocator.h>
#include <luisa/vstl/string_hash.h>
#include <luisa/vstl/string_utility.h>
#include <luisa/vstl/tree_map_base.h>
#include <luisa/vstl/unique_ptr.h>
#include <luisa/vstl/v_allocator.h>
#include <luisa/vstl/v_guid.h>
#include <luisa/vstl/vector.h>
#include <luisa/vstl/vstring.h>

