//
// Created by mike on 9/17/25.
//

#pragma once

#define LUISA_COMPUTE_VERSION_MAJOR 0
#define LUISA_COMPUTE_VERSION_MINOR 9
#define LUISA_COMPUTE_VERSION_PATCH 0

#define LUISA_COMPUTE_VERSION (LUISA_COMPUTE_VERSION_MAJOR * 10000 + LUISA_COMPUTE_VERSION_MINOR * 100 + LUISA_COMPUTE_VERSION_PATCH)
