"""
Type stub file for luisa package.
"""

from luisa.dsl_types import (
    Type as Type,
    Scalar as Scalar,
    Vector as Vector,
    Matrix as Matrix,
    Array as Array,
    Struct as Struct,
    Buffer as Buffer,
    Texture2D as Texture2D,
    Texture3D as Texture3D,
    BindlessArray as BindlessArray,
    Accel as Accel,
    RayQuery as RayQuery,
    Callable as Callable,
    Void as Void,
    bool_ as bool_,
    int8 as int8,
    uint8 as uint8,
    int16 as int16,
    uint16 as uint16,
    int32 as int32,
    uint32 as uint32,
    int64 as int64,
    uint64 as uint64,
    float16 as float16,
    float32 as float32,
    float64 as float64,
    int2 as int2,
    int3 as int3,
    int4 as int4,
    uint2 as uint2,
    uint3 as uint3,
    uint4 as uint4,
    float2 as float2,
    float3 as float3,
    float4 as float4,
    bool2 as bool2,
    bool3 as bool3,
    bool4 as bool4,
    half2 as half2,
    half3 as half3,
    half4 as half4,
    short2 as short2,
    short3 as short3,
    short4 as short4,
    ushort2 as ushort2,
    ushort3 as ushort3,
    ushort4 as ushort4,
    long2 as long2,
    long3 as long3,
    long4 as long4,
    ulong2 as ulong2,
    ulong3 as ulong3,
    ulong4 as ulong4,
    float2x2 as float2x2,
    float3x3 as float3x3,
    float4x4 as float4x4,
    get_element_type as get_element_type,
    get_length as get_length,
    is_scalar_type as is_scalar_type,
    is_vector_type as is_vector_type,
    is_integer_type as is_integer_type,
    is_float_type as is_float_type,
    promote_types as promote_types,
)

from luisa.ir import (
    IROp as IROp,
    Value as Value,
    ConstantValue as ConstantValue,
    ArgumentValue as ArgumentValue,
    InstructionValue as InstructionValue,
    IRInstruction as IRInstruction,
    IRBasicBlock as IRBasicBlock,
    IRFunction as IRFunction,
    IRModule as IRModule,
)

from luisa.builder import IRBuilder as IRBuilder

from luisa.staged import (
    StagedFunction as StagedFunction,
    kernel as kernel,
    callable as callable,
)

from luisa.builtins import (
    sqrt as sqrt,
    abs as abs,
    sin as sin,
    cos as cos,
    tan as tan,
    asin as asin,
    acos as acos,
    atan as atan,
    atan2 as atan2,
    exp as exp,
    exp2 as exp2,
    log as log,
    log2 as log2,
    log10 as log10,
    floor as floor,
    ceil as ceil,
    round as round,
    trunc as trunc,
    fract as fract,
    saturate as saturate,
    normalize as normalize,
    length as length,
    length_squared as length_squared,
    min as min,
    max as max,
    clamp as clamp,
    lerp as lerp,
    step as step,
    smoothstep as smoothstep,
    pow as pow,
    dot as dot,
    cross as cross,
    distance as distance,
    reflect as reflect,
    refract as refract,
    faceforward as faceforward,
    transpose as transpose,
    inverse as inverse,
    determinant as determinant,
)

__version__: str
