"""
Type stub file for builder.py
"""

from __future__ import annotations
from typing import Optional, Union, Any, List, Tuple, TYPE_CHECKING
from contextlib import contextmanager
from dataclasses import dataclass

if TYPE_CHECKING:
    from .dsl_types import Type
    from .ir import Value, ConstantValue, IRInstruction, IRBasicBlock, IRFunction, IROp

@dataclass
class LoopContext:
    header_block: IRBasicBlock
    exit_block: IRBasicBlock

class IRBuilder:
    name: str
    arg_types: List[Type]
    ret_type: Optional[Type]
    blocks: List[IRBasicBlock]
    current_block: Optional[IRBasicBlock]
    instruction_counter: int
    local_vars: dict[str, Value]
    loop_stack: List[LoopContext]
    arg_values: List[ArgumentValue]
    
    def __init__(self, name: str, arg_types: Tuple[Type, ...], ret_type: Optional[Type]) -> None: ...
    
    # Value Creation
    def constant(self, type: Type, value: Any) -> ConstantValue: ...
    def get_argument(self, index: int) -> ArgumentValue: ...
    def bind_local(self, name: str, value: Value) -> None: ...
    def lookup_local(self, name: str) -> Optional[Value]: ...
    
    # Block Management
    def create_block(self, name: str) -> IRBasicBlock: ...
    def set_insert_point(self, block: IRBasicBlock) -> None: ...
    def get_insert_point(self) -> Optional[IRBasicBlock]: ...
    
    # Instruction Emission
    def _emit(self, op: IROp, type: Type, args: List[Any], name: Optional[str] = None) -> InstructionValue: ...
    
    # Arithmetic Operations
    def add(self, left: Value, right: Value, result_type: Optional[Type] = None) -> InstructionValue: ...
    def sub(self, left: Value, right: Value, result_type: Optional[Type] = None) -> InstructionValue: ...
    def mul(self, left: Value, right: Value, result_type: Optional[Type] = None) -> InstructionValue: ...
    def div(self, left: Value, right: Value, result_type: Optional[Type] = None) -> InstructionValue: ...
    def neg(self, operand: Value) -> InstructionValue: ...
    
    # Comparison Operations
    def eq(self, left: Value, right: Value) -> InstructionValue: ...
    def ne(self, left: Value, right: Value) -> InstructionValue: ...
    def lt(self, left: Value, right: Value) -> InstructionValue: ...
    def le(self, left: Value, right: Value) -> InstructionValue: ...
    def gt(self, left: Value, right: Value) -> InstructionValue: ...
    def ge(self, left: Value, right: Value) -> InstructionValue: ...
    
    # Logical Operations
    def logical_and(self, left: Value, right: Value) -> InstructionValue: ...
    def logical_or(self, left: Value, right: Value) -> InstructionValue: ...
    def logical_not(self, operand: Value) -> InstructionValue: ...
    
    # Memory Operations
    def alloca(self, type: Type, name: Optional[str] = None) -> InstructionValue: ...
    def load(self, ptr: Value, type: Optional[Type] = None) -> InstructionValue: ...
    def store(self, ptr: Value, value: Value) -> InstructionValue: ...
    
    # Control Flow - Branches
    def branch(self, target: IRBasicBlock) -> IRInstruction: ...
    def branch_conditional(self, cond: Value, true_target: IRBasicBlock, false_target: IRBasicBlock) -> IRInstruction: ...
    def return_(self, value: Optional[Value] = None) -> IRInstruction: ...
    
    # Control Flow - High Level (Context Managers)
    def if_(self, cond: Value) -> IfScope: ...
    def while_(self, cond: Value) -> WhileScope: ...
    def for_range(self, start: Value, stop: Value, step: Value, loop_var: str) -> ForRangeScope: ...
    def for_unrolled(self, start: int, stop: int, step: int, loop_var: str) -> UnrolledForScope: ...
    def switch(self, value: Value) -> SwitchScope: ...
    def break_(self) -> None: ...
    def continue_(self) -> None: ...
    def push_loop(self, header: IRBasicBlock, exit_block: IRBasicBlock) -> None: ...
    def pop_loop(self) -> None: ...
    
    # Build
    def build(self) -> IRFunction: ...

# Control Flow Scopes

class IfScope:
    builder: IRBuilder
    condition: Value
    true_block: Optional[IRBasicBlock]
    false_block: Optional[IRBasicBlock]
    merge_block: Optional[IRBasicBlock]
    has_false_branch: bool
    _folded: bool
    _fold_result: Optional[bool]
    
    def __init__(self, builder: IRBuilder, condition: Value) -> None: ...
    def __enter__(self) -> IfScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def otherwise(self) -> Union[ElseScope, NoOpScope, DirectScope]: ...

class ElseScope:
    builder: IRBuilder
    merge_block: IRBasicBlock
    
    def __init__(self, builder: IRBuilder, merge_block: IRBasicBlock) -> None: ...
    def __enter__(self) -> ElseScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class NoOpScope:
    builder: IRBuilder
    
    def __init__(self, builder: IRBuilder) -> None: ...
    def __enter__(self) -> NoOpScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def otherwise(self) -> DirectScope: ...

class DirectScope:
    builder: IRBuilder
    
    def __init__(self, builder: IRBuilder) -> None: ...
    def __enter__(self) -> DirectScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def otherwise(self) -> NoOpScope: ...

class WhileScope:
    builder: IRBuilder
    condition: Value
    header_block: Optional[IRBasicBlock]
    body_block: Optional[IRBasicBlock]
    exit_block: Optional[IRBasicBlock]
    
    def __init__(self, builder: IRBuilder, condition: Value) -> None: ...
    def __enter__(self) -> WhileScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class ForRangeScope:
    builder: IRBuilder
    start: Value
    stop: Value
    step: Value
    loop_var_name: str
    loop_var: Optional[InstructionValue]
    header_block: Optional[IRBasicBlock]
    body_block: Optional[IRBasicBlock]
    exit_block: Optional[IRBasicBlock]
    
    def __init__(self, builder: IRBuilder, start: Value, stop: Value, step: Value, loop_var_name: str) -> None: ...
    def __enter__(self) -> ForRangeScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class UnrolledForScope:
    builder: IRBuilder
    start: int
    stop: int
    step: int
    loop_var_name: str
    iterations: List[int]
    current_iteration: int
    
    def __init__(self, builder: IRBuilder, start: int, stop: int, step: int, loop_var_name: str) -> None: ...
    def __enter__(self) -> UnrolledForScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def _bind_iteration(self, idx: int) -> bool: ...
    def next_iteration(self) -> bool: ...

class SwitchScope:
    builder: IRBuilder
    value: Value
    cases: List[Tuple[List[int], IRBasicBlock]]
    default_block: Optional[IRBasicBlock]
    exit_block: Optional[IRBasicBlock]
    _folded: bool
    _constant_value: Any
    
    def __init__(self, builder: IRBuilder, value: Value) -> None: ...
    def __enter__(self) -> SwitchScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def case(self, *values: int) -> Union[CaseScope, NoOpScope, DirectScope]: ...
    def default(self) -> Union[CaseScope, NoOpScope, DirectScope]: ...

class CaseScope:
    builder: IRBuilder
    case_block: IRBasicBlock
    exit_block: IRBasicBlock
    
    def __init__(self, builder: IRBuilder, case_block: IRBasicBlock, exit_block: IRBasicBlock) -> None: ...
    def __enter__(self) -> CaseScope: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
