"""
Type stub file for dsl_types.py
"""

from __future__ import annotations
from typing import Optional, Union, Any, Tuple
from enum import Enum
from dataclasses import dataclass

class ScalarType(Enum):
    BOOL = ...
    INT8 = ...
    UINT8 = ...
    INT16 = ...
    UINT16 = ...
    INT32 = ...
    UINT32 = ...
    INT64 = ...
    UINT64 = ...
    FLOAT16 = ...
    FLOAT32 = ...
    FLOAT64 = ...

@dataclass(frozen=True)
class Type:
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Scalar(Type):
    dtype: ScalarType
    def __init__(self, dtype: ScalarType) -> None: ...
    def __repr__(self) -> str: ...
    @classmethod
    def bool(cls) -> Scalar: ...
    @classmethod
    def int8(cls) -> Scalar: ...
    @classmethod
    def uint8(cls) -> Scalar: ...
    @classmethod
    def int16(cls) -> Scalar: ...
    @classmethod
    def uint16(cls) -> Scalar: ...
    @classmethod
    def int32(cls) -> Scalar: ...
    @classmethod
    def uint32(cls) -> Scalar: ...
    @classmethod
    def int64(cls) -> Scalar: ...
    @classmethod
    def uint64(cls) -> Scalar: ...
    @classmethod
    def float16(cls) -> Scalar: ...
    @classmethod
    def float32(cls) -> Scalar: ...
    @classmethod
    def float64(cls) -> Scalar: ...

@dataclass(frozen=True)
class Vector(Type):
    element: Scalar
    size: int
    def __init__(self, element: Scalar, size: int) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Matrix(Type):
    element: Scalar
    size: int
    def __init__(self, element: Scalar, size: int) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Array(Type):
    element: Type
    size: int
    def __init__(self, element: Type, size: int) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Struct(Type):
    name: str
    fields: Tuple[Tuple[str, Type], ...]
    alignment: int
    def __init__(self, name: str, fields: Tuple[Tuple[str, Type], ...], alignment: int = 4) -> None: ...
    def __repr__(self) -> str: ...
    def get_field_type(self, field_name: str) -> Optional[Type]: ...
    def get_field_index(self, field_name: str) -> int: ...

@dataclass(frozen=True)
class Buffer(Type):
    element: Type
    def __init__(self, element: Type) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Texture2D(Type):
    element: Scalar
    def __init__(self, element: Scalar) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Texture3D(Type):
    element: Scalar
    def __init__(self, element: Scalar) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class BindlessArray(Type):
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Accel(Type):
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class RayQuery(Type):
    query_any: bool
    def __init__(self, query_any: bool) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Callable(Type):
    arg_types: Tuple[Type, ...]
    ret_type: Optional[Type]
    def __init__(self, arg_types: Tuple[Type, ...], ret_type: Optional[Type]) -> None: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True)
class Void(Type):
    def __repr__(self) -> str: ...

# Type alias
AnyType = Union[Scalar, Vector, Matrix, Array, Struct, Buffer, Texture2D, Texture3D, BindlessArray, Accel, RayQuery, Callable, Void]

# Predefined scalar types
bool_: Scalar
int8: Scalar
uint8: Scalar
int16: Scalar
uint16: Scalar
int32: Scalar
uint32: Scalar
int64: Scalar
uint64: Scalar
float16: Scalar
float32: Scalar
float64: Scalar

# Short aliases
int_: Scalar
uint: Scalar
float_: Scalar

# Predefined vector types
int2: Vector
int3: Vector
int4: Vector
uint2: Vector
uint3: Vector
uint4: Vector
float2: Vector
float3: Vector
float4: Vector
bool2: Vector
bool3: Vector
bool4: Vector
half2: Vector
half3: Vector
half4: Vector
short2: Vector
short3: Vector
short4: Vector
ushort2: Vector
ushort3: Vector
ushort4: Vector
long2: Vector
long3: Vector
long4: Vector
ulong2: Vector
ulong3: Vector
ulong4: Vector

# Matrix types
float2x2: Matrix
float3x3: Matrix
float4x4: Matrix

# Utility functions
def get_element_type(t: Type) -> Type: ...
def get_length(t: Type) -> int: ...
def is_scalar_type(t: Type) -> bool: ...
def is_vector_type(t: Type) -> bool: ...
def is_matrix_type(t: Type) -> bool: ...
def is_arithmetic_type(t: Type) -> bool: ...
def is_integer_type(t: Type) -> bool: ...
def is_float_type(t: Type) -> bool: ...
def is_bool_type(t: Type) -> bool: ...
def is_resource_type(t: Type) -> bool: ...
def promote_types(t1: Type, t2: Type) -> Type: ...
def python_type_to_dsl(py_type: type) -> Optional[Type]: ...
def get_broadcast_type(t1: Type, t2: Type) -> Optional[Type]: ...
def value_to_type(value: Any) -> Optional[Type]: ...
