"""
Type stub file for ir.py
"""

from __future__ import annotations
from typing import Optional, Union, Any, List, TYPE_CHECKING
from dataclasses import dataclass, field
from enum import Enum

if TYPE_CHECKING:
    from .dsl_types import Type

class IROp(Enum):
    # Literals and constants
    CONST = ...
    # Arithmetic
    ADD = ...
    SUB = ...
    MUL = ...
    DIV = ...
    MOD = ...
    NEG = ...
    # Bitwise
    BIT_AND = ...
    BIT_OR = ...
    BIT_XOR = ...
    BIT_NOT = ...
    SHL = ...
    SHR = ...
    # Comparison
    EQ = ...
    NE = ...
    LT = ...
    LE = ...
    GT = ...
    GE = ...
    # Logical
    LOGICAL_AND = ...
    LOGICAL_OR = ...
    LOGICAL_NOT = ...
    # Math functions
    SQRT = ...
    POW = ...
    EXP = ...
    EXP2 = ...
    LOG = ...
    LOG2 = ...
    LOG10 = ...
    SIN = ...
    COS = ...
    TAN = ...
    ASIN = ...
    ACOS = ...
    ATAN = ...
    ATAN2 = ...
    SINH = ...
    COSH = ...
    TANH = ...
    ABS = ...
    MIN = ...
    MAX = ...
    CLAMP = ...
    LERP = ...
    SATURATE = ...
    STEP = ...
    SMOOTHSTEP = ...
    DOT = ...
    CROSS = ...
    NORMALIZE = ...
    LENGTH = ...
    LENGTH_SQUARED = ...
    DISTANCE = ...
    REFLECT = ...
    REFRACT = ...
    FACEFORWARD = ...
    # Matrix operations
    MATRIX_DETERMINANT = ...
    MATRIX_TRANSPOSE = ...
    MATRIX_INVERSE = ...
    # Memory
    ALLOCA = ...
    LOAD = ...
    STORE = ...
    GEP = ...
    MEMBER_ACCESS = ...
    # Resources
    BUFFER_READ = ...
    BUFFER_WRITE = ...
    BUFFER_SIZE = ...
    TEXTURE2D_READ = ...
    TEXTURE2D_WRITE = ...
    TEXTURE2D_SAMPLE = ...
    TEXTURE2D_SAMPLE_LEVEL = ...
    TEXTURE3D_READ = ...
    TEXTURE3D_WRITE = ...
    TEXTURE3D_SAMPLE = ...
    # Control flow
    BR = ...
    COND_BR = ...
    PHI = ...
    RETURN = ...
    # Function calls
    CALL = ...
    CALL_BUILTIN = ...
    # Cast
    CAST = ...
    BITCAST = ...
    # Special registers
    THREAD_ID = ...
    BLOCK_ID = ...
    DISPATCH_ID = ...
    DISPATCH_SIZE = ...
    KERNEL_ID = ...
    OBJECT_ID = ...
    # Ray tracing
    TRACE_CLOSEST = ...
    TRACE_ANY = ...
    RAY_QUERY_ALL = ...
    RAY_QUERY_ANY = ...
    # Atomic operations
    ATOMIC_EXCHANGE = ...
    ATOMIC_ADD = ...
    ATOMIC_SUB = ...
    ATOMIC_AND = ...
    ATOMIC_OR = ...
    ATOMIC_XOR = ...
    ATOMIC_MIN = ...
    ATOMIC_MAX = ...
    ATOMIC_CMP_EXCH = ...
    # Warp operations
    WARP_SUM = ...
    WARP_PRODUCT = ...
    WARP_MIN = ...
    WARP_MAX = ...
    WARP_ALL = ...
    WARP_ANY = ...
    WARP_BROADCAST = ...
    WARP_PREFIX_SUM = ...
    WARP_PREFIX_PRODUCT = ...
    # Synchronization
    SYNC_BLOCK = ...
    # Print
    PRINT = ...
    # Swizzle
    SWIZZLE = ...

@dataclass
class Value:
    type: Type
    name: Optional[str]
    def __init__(self, type: Type, name: Optional[str] = None) -> None: ...
    def __repr__(self) -> str: ...

@dataclass
class ConstantValue(Value):
    value: Any
    def __init__(self, type: Type, value: Any, name: Optional[str] = None) -> None: ...
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...

@dataclass
class ArgumentValue(Value):
    index: int
    def __init__(self, type: Type, index: int, name: Optional[str] = None) -> None: ...
    def __post_init__(self) -> None: ...

@dataclass
class InstructionValue(Value):
    instruction: Optional[IRInstruction]
    def __init__(self, type: Type, name: Optional[str] = None, instruction: Optional[IRInstruction] = None) -> None: ...
    def __repr__(self) -> str: ...

@dataclass
class IRInstruction:
    op: IROp
    type: Type
    args: List[Union[int, str, Value]]
    result: Optional[str]
    def __init__(self, op: IROp, type: Type, args: List[Union[int, str, Value]] = ..., result: Optional[str] = None) -> None: ...
    def __repr__(self) -> str: ...

@dataclass
class IRBasicBlock:
    name: str
    instructions: List[IRInstruction]
    def __init__(self, name: str, instructions: Optional[List[IRInstruction]] = None) -> None: ...
    def __repr__(self) -> str: ...
    def is_terminated(self) -> bool: ...
    def add_instruction(self, inst: IRInstruction) -> None: ...

@dataclass
class IRFunction:
    name: str
    arg_types: List[Type]
    ret_type: Optional[Type]
    blocks: List[IRBasicBlock]
    is_kernel: bool
    block_size: Optional[Tuple[int, int, int]]
    def __init__(self, name: str, arg_types: List[Type], ret_type: Optional[Type], blocks: Optional[List[IRBasicBlock]] = None, is_kernel: bool = False, block_size: Optional[Tuple[int, int, int]] = None) -> None: ...
    def __repr__(self) -> str: ...
    def get_block(self, name: str) -> Optional[IRBasicBlock]: ...

@dataclass
class IRModule:
    functions: List[IRFunction]
    constants: List[ConstantValue]
    def __init__(self, functions: Optional[List[IRFunction]] = None, constants: Optional[List[ConstantValue]] = None) -> None: ...
    def __repr__(self) -> str: ...
    def add_function(self, func: IRFunction) -> None: ...
    def get_function(self, name: str) -> Optional[IRFunction]: ...

# Utility functions
def get_op_name(op: IROp) -> str: ...
def is_arithmetic_op(op: IROp) -> bool: ...
def is_comparison_op(op: IROp) -> bool: ...
def is_logical_op(op: IROp) -> bool: ...
def is_terminator_op(op: IROp) -> bool: ...
def is_memory_op(op: IROp) -> bool: ...
def is_resource_op(op: IROp) -> bool: ...
