"""
Type stub file for staged.py
"""

from __future__ import annotations
from typing import Callable, Optional, Any, TYPE_CHECKING, Union, Tuple, Dict

if TYPE_CHECKING:
    from .dsl_types import Type
    from .ir import IRFunction, Value
    from .parser import ParsedFunction
    from .builder import IRBuilder

class StagedFunction:
    """
    A staged function that generates IR when called.
    
    This is the core of multistage programming - the actual IR generation
    is deferred until the function is called with specific argument types.
    """
    
    pyfunc: Callable
    is_kernel: bool
    parsed: ParsedFunction
    _cache: Dict[Tuple[Type, ...], IRFunction]
    
    def __init__(self, func: Callable, is_kernel: bool = False) -> None: ...
    
    @property
    def name(self) -> str: ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> IRFunction: ...
    
    def _get_arg_type(self, arg: Any) -> Type: ...

class BuilderExecutor:
    """
    Execute the Python AST using the IR builder.
    
    This interprets the Python AST and calls the appropriate builder methods.
    It's essentially a Python interpreter that generates IR instead of executing.
    """
    
    builder: IRBuilder
    parsed: ParsedFunction
    captured_vars: Dict[str, Any]
    arg_values: Tuple[Any, ...]
    local_vars: Dict[str, Value]
    
    def __init__(self, builder: IRBuilder, parsed: ParsedFunction, 
                 captured_vars: Dict[str, Any], arg_values: Tuple[Any, ...]) -> None: ...
    
    def execute(self) -> None: ...
    def visit(self, node: Any) -> Optional[Any]: ...
    def generic_visit(self, node: Any) -> None: ...
    
    # Statement visitors
    def visit_Expr(self, node: Any) -> None: ...
    def visit_Assign(self, node: Any) -> None: ...
    def visit_AnnAssign(self, node: Any) -> None: ...
    def visit_Return(self, node: Any) -> None: ...
    def visit_If(self, node: Any) -> None: ...
    def visit_While(self, node: Any) -> None: ...
    def visit_For(self, node: Any) -> None: ...
    def _visit_for_range(self, node: Any) -> None: ...
    def visit_Pass(self, node: Any) -> None: ...
    
    # Expression visitors
    def visit_Constant(self, node: Any) -> Any: ...
    def visit_Name(self, node: Any) -> Any: ...
    def visit_BinOp(self, node: Any) -> Any: ...
    def visit_UnaryOp(self, node: Any) -> Any: ...
    def visit_Compare(self, node: Any) -> Any: ...
    def visit_Call(self, node: Any) -> Any: ...
    def visit_Attribute(self, node: Any) -> Any: ...
    def visit_Subscript(self, node: Any) -> Any: ...

def kernel(func: Callable) -> StagedFunction:
    """Decorator to mark a function as a kernel."""
    ...

def callable(func: Callable) -> StagedFunction:
    """Decorator to mark a function as a callable device function."""
    ...
